### ISSUE TITLE
npm install mongo-edu -g

### ISSUE THREAD

**Issue by tapan-d-thakkar** [przemyslawpluta/mongo-edu#25]
When I ran npm install mongo-edu -g command i get below error ..

npm http GET https://registry.npmjs.org/once/-/once-1.3.1.tgz
npm ERR! youtube-dl@1.5.13 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the youtube-dl@1.5.13 preinstall script.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install" "mongo-edu" "-g"
npm ERR! cwd C:\Users\5013003276
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm http GET https://registry.npmjs.org/tough-cookie/-/tough-cookie-0.12.1.tgz
npm http GET https://registry.npmjs.org/minimatch/-/minimatch-1.0.0.tgz

after this if i run mongo-edu --help it says command not found.

**Comment by rndmax** [comment]
Hello! i have same problem. Node v5.0.0;  Python 2.7.10;  Npm 3.3.6
