### ISSUE TITLE
no subtitles downloaded

### ISSUE THREAD

**Issue by przemyslawpluta** [przemyslawpluta/mongo-edu#37]
Ref [node-youtube-dl/issues/48](https://github.com/fent/node-youtube-dl/issues/48)

**Comment by toriet** [comment]
i´m downloading the m202 with mongo-edu 0.2.3 and... there isn't subtitles :(

**Comment by przemyslawpluta** [comment]
Add `--cc` to args.

**Comment by toriet** [comment]
only with --cc don´t work, if you add --cw it works, thanks.
