### ISSUE TITLE
Unable to open download window

### ISSUE THREAD

**Issue by fkhalid28** [przemyslawpluta/mongo-edu#38]
Hi,
I have installed mongo-edu on my desktop computer running windows2008.
When I try to start the download, it just hang at following step without going into download prompt.

-----------------------------------------
C:\1. My Office Data\New Downloads>mongo-edu -d 'C:\' -u fk36@hotmail.com --cw

 [ MONGO-EDU 0.2.4 ]

----------------------------------------------------
Any help on this will be highly appreciated.

**Comment by fkhalid28** [comment]
When I click control-C it ask be below confirmation.

C:\>mongo-edu -d 'C:\' -u fk36@hotmail.com --cw


 [ MONGO-EDU 0.2.4 ]


^CTerminate batch job (Y/N)? Y


Following are the per-requisites i had installed prior to mongo-edu installation.

C:\>node -v
v0.10.35

C:\>npm -v
1.4.28

C:\>python -V
Python 2.7.9

C:\>

**Comment by przemyslawpluta** [comment]
`win2008` is not really supported ... unfortunately I don't have any means of testing this on this OS

**Comment by fkhalid28** [comment]
I have exactly same problem on windows 2007 too. It just stuck at this stage.
I tried to uninstall Python (after reading the previous threads) but that didn't work either.

**Comment by przemyslawpluta** [comment]
Anything below `win7` is not really supported as I don't have any way of testing it. You could use vmware or make an ubuntu bootable partition or usb drive ...

**Comment by fkhalid28** [comment]
I agree that win2008 has problem but i am experiencing the same problem on win7 too as I mentioned above. Any idea about this?

**Comment by przemyslawpluta** [comment]
Above you've mentioned `win 2007` ( vista ) which is a predecessor of windows 7.

**Comment by fkhalid28** [comment]
Hi,
Sorry for not making the environment settings clear. Can you please confirm if following environment is not supported? My colleague is having same windows and he is able to use this tool without any issues.

OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation

**Comment by przemyslawpluta** [comment]
OK so we're talking about `win7` then. Are you and your collegue on the same network? If not are you using the tool from home or work network?

**Comment by fkhalid28** [comment]
We are on the same office network.
Infect it was working fine on my computer till two days ago when my windows was reinstalled by helpdesk and now i tried to install everything and somehow this tools is not working anymore.

**Comment by przemyslawpluta** [comment]
Your current download path `-d 'C:\'` doesn't point into any directory ... just root
```
mongo-edu -d 'C:\' -u fk36@hotmail.com --cw
```
so do this instead
```
mongo-edu -d 'C:\videos\' -u fk36@hotmail.com --cw
```

**Comment by fkhalid28** [comment]
It's Same result.
========================================
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\farooq.khalid>mongo-edu -d 'C:\Temp\' -u fk36@hotmail.com --cw

 [ MONGO-EDU 0.2.4 ]


==========================

**Comment by przemyslawpluta** [comment]
Without the quotes ...

```
mongo-edu -d C:\Temp\ -u fk36@hotmail.com --cw
```

**Comment by fkhalid28** [comment]
thanks this worked now.

**Comment by przemyslawpluta** [comment]
For the future reference if there are no spaces in the path to your directory you don't have to use any quotes e.g.
```
mongo-edu -d C:\my\newDirectory\ -u user@mail.com --cw
```
... if the path contains spaces use double quotes
```
mongo-edu -d "C:\my\new Directory\" -u user@mail.com --cw
```

**Comment by fkhalid28** [comment]
Thanks I will remember this.

Btw Now I am getting following message randomly.  Yesterday I got this twice and then it was successful. Today I tried again and got following message.
===================================================
C:\Users\farooq.khalid>mongo-edu -d C:\Temp\ -u fk36@hotmail.com --cw


 [ MONGO-EDU 0.2.4 ]


? MongoDB Uni User Name: fk36@hotmail.com
? MongoDB Uni Password: ***********
> Searching [====================] 100%
? Found 2 Courses. Select: M202: MongoDB Advanced Deployment and Operations
? Found 4 Lists. Select: Chapter 4: Fault Tolerance and Availability
> Searching Courseware [====================] 100%
> Collecting [====================] 100%
? Select From 18 Videos. Download: All
i Downloading: 1 0 Rolling maintenance-OO3tpaC4L4g.mp4 > https://youtu.be/OO3tpaC4L4g
> 20.91 MB [====================] 100% 0.0s
i 1 0 Rolling maintenance-OO3tpaC4L4g.mp4. Done in: 46419ms
i 17 left ...
i Downloading: rolling maintenance answer-L2tv_OC31uQ.mp4 > https://youtu.be/L2tv_OC31uQ
> 953.52 kB [====================] 100% 0.0s
i rolling maintenance answer-L2tv_OC31uQ.mp4. Done in: 1864ms
i 16 left ...
i Downloading: 1 1 Rolling maintenance use cases-LH22a2FATho.mp4 > https://youtu.be/LH22a2FATho
> 4.8 MB [====================] 100% 0.0s
i 1 1 Rolling maintenance use cases-LH22a2FATho.mp4. Done in: 8632ms
i 15 left ...
i Downloading: 2 0 Can I put a load balancer in front of a replica set-fqcDrfwvygU.mp4 > https://youtu.be/fqcDrfwvygU
> 8.58 MB [====================] 100% 0.0s
i 2 0 Can I put a load balancer in front of a replica set-fqcDrfwvygU.mp4. Done in: 14388ms
i 14 left ...
i Downloading: 2 1 Using load balancers with sharded clusters-LW_mlmvwWDM.mp4 > https://youtu.be/LW_mlmvwWDM
> 15.39 MB [====================] 100% 0.0s
i 2 1 Using load balancers with sharded clusters-LW_mlmvwWDM.mp4. Done in: 32635ms
i 13 left ...
Error: : [youtube] -kzJ44CbCsM: Skipping DASH manifest: ExtractorError(u'Cannot decrypt signature without player_url; please report this issue on https://yt-dl.org/bug . Make sure you a
re using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)

    at C:\Users\farooq.khalid\AppData\Roaming\npm\node_modules\mongo-edu\node_modules\youtube-dl\lib\youtube-dl.js:148:25
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
===================================================

**Comment by przemyslawpluta** [comment]
Can't replicate ... also this error looks more like `youtube-dl` issue not `mongo-edu`. By the way I'd suggest downloading the videos again as it looks like they've updated the list as I counted `14 videos` now not `18 videos`.

**Comment by fkhalid28** [comment]
I have taken too much time of yours.
This issue is not consistent. Some time it occurs and sometime i am able to download full chapter.
I will retry if it failed with this error again.
