### ISSUE TITLE
Searching Courseware always stops at the last.

### ISSUE THREAD

**Issue by SanketDG** [przemyslawpluta/mongo-edu#39]
Whenever I am trying to download a week it always fails.
It just stops in the searching courseware progress at any arbitrary number.
![blah](http://i.imgur.com/aeZqSY3.png)

**Comment by przemyslawpluta** [comment]
Can't reproduce ... just tested with the latest version `0.2.5` on `*nix, mac os*, win*` and works without any issues.

**Comment by SanketDG** [comment]
Could you specifically check m101p..I have all the dependencies installed, I am quite confused to what's causing this.

**Comment by przemyslawpluta** [comment]
Tested against `m101p` works fine on my side. Try to bump up to `v0.2.5` ... looks like network issues ...

**Comment by SanketDG** [comment]
Bumped it up..now it just hangs at the `Collecting` after `Searching Courseware` at 99%

**Comment by przemyslawpluta** [comment]
What `OS` and `node` version do you on?

**Comment by SanketDG** [comment]
I am on Linux Mint 17
`node -v` shows `v0.10.33`

Just checked again, and it works. So its probably a network issue. Can't be a system issue.

**Comment by przemyslawpluta** [comment]
Cool. Network :)

**Comment by SanketDG** [comment]
Yeah. Thanks.

**Comment by cameronliam** [comment]
Hi,
I am getting the same problem, also downloading M101P. 'Searching Courseware' always hangs when it reaches ~%80 (min: 73%, max: 93%). Tried it on multiple networks, same result. Any advice?

OS X 10.10.5
Node v4.3.1
