### ISSUE TITLE
Not all handouts are shown

### ISSUE THREAD

**Issue by ikixxx** [przemyslawpluta/mongo-edu#40]
When I try to download the handouts for mongdb nodejs course. It lists only first 6 weeks. 
So no week 7 and final exam. But if I decide to download all handouts , it will download week 7 and exam handouts.

**Comment by przemyslawpluta** [comment]
Can't replicate on my side. Just tested against `0.2.5` and `M101JS` handouts and I can see all handouts listed from week 1 to week 7 including final exam. Selecting `All` downloads all listed items as expected.

**Comment by ikixxx** [comment]
My mistake, I needed to scroll the page in order to see all the results.
