### ISSUE TITLE
youtube-dl

### ISSUE THREAD

**Issue by bargom** [przemyslawpluta/mongo-edu#42]
This module keeps on giving error while installation.

npm http GET https://registry.npmjs.org/youtube-dl
npm http 304 https://registry.npmjs.org/youtube-dl

> youtube-dl@1.10.2 preinstall /home/baris/offline/node_modules/youtube-dl
> node ./scripts/download.js

npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! youtube-dl@1.10.2 preinstall: `node ./scripts/download.js`
npm ERR! `sh "-c" "node ./scripts/download.js"` failed with 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.10.2 preinstall script.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.11.0-26-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "youtube-dl"
npm ERR! cwd /home/baris/offline
npm ERR! node -v v0.10.15
npm ERR! npm -v 1.2.18
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/baris/offline/npm-debug.log
npm ERR! not ok code 0

**Comment by przemyslawpluta** [comment]
Looks like it's the same as https://github.com/przemyslawpluta/mongo-edu/issues/36 try `apt-get install nodejs-legacy` with `sudo` if required then install `mongo-edu` again.
