### ISSUE TITLE
Week 4 of M102 and M101P creates error

### ISSUE THREAD

**Issue by dmr173** [przemyslawpluta/mongo-edu#43]
Hi,
I tried to download the videos of the MongoDB University for courses M102 and M101P this week and got errors and the download didn't complete. Command used was:

-d path -u my_email --cw --hq

Then I selected the respective course, the chapter(week) and All videos from this chapter. This works fine for chapters/weeks 1 to 3 but the script doesn't finish for week 4. Is this a known issue? Shall I post the error output I see in the command prompt of Windows 8 ? What other details do you need?
Thanks
Dmr

**Comment by przemyslawpluta** [comment]
Just downloaded entire `Chapter4: Replication` from `M102` without any issues. There are sometimes issues with `youtube` so you might try to run it again later on and let me know the outcome.

P

**Comment by przemyslawpluta** [comment]
This should be fixed now just bump it up to latest `mongo-edu v0.2.7`.
