### ISSUE TITLE
Error message youtube options

### ISSUE THREAD

**Issue by dmr173** [przemyslawpluta/mongo-edu#44]
After upgrading mongo-edu today, I get the following error when trying to download videos in high quality (didn't try without high quality yet):

C:\************\mongodb\offline_videos\M102>mongo-edu -d .\Week7 -u **********@gmail.com --hq --cw

 [ MONGO-EDU 0.2.9 ]

? MongoDB Uni User Name: **********@gmail.com
? MongoDB Uni Password: ******
> Searching [====================] 100%
? Found 3 Courses. Select: M102: MongoDB for DBAs
? Found 8 Lists. Select: Chapter 7: Backup and Recovery
> Searching Courseware [====================] 100%
> Collecting [====================] 100%
? Select From 1 Videos. Download: All
Error: Command failed: python C:\Users\dmr\AppData\Roaming\npm\node_modules\mongo-edu\node_modules\youtube-dl\bin\youtub
e-dl --dump-json --max-quality=22 https://youtu.be/1n0IDMAWR0Y
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: no such option: --max-quality

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

C:\Users\dmr\mongodb\offline_videos\M102>

**Comment by dmr173** [comment]
Same behaviour if I call it without "--hq"

**Comment by przemyslawpluta** [comment]
Latest release of `youtube-dl` seems to introduce changes to the API https://github.com/rg3/youtube-dl/issues/5550 will update when I have a minute.

**Comment by przemyslawpluta** [comment]
Done. Just update to the latest version `mongo-edu v0.2.10`
