### ISSUE TITLE
Could not locate any videos

### ISSUE THREAD

**Issue by ravimohankaivar** [przemyslawpluta/mongo-edu#46]
I am unable to download any videos. Please help. Below is the command I used. after selecting the chapter in the list, it says "Could not locate any videos". Note: In the UserName tab I have put asterisks to hide the username here. 

Thanks.

C:\Users\RMK>mongo-edu -d G:\MongoDB_CourseWare --cw

 [ MONGO-EDU 0.2.11 ]

? MongoDB Uni User Name: r**********@********.com
? MongoDB Uni Password: ***********
> Searching [====================] 100%
? Found 4 Courses. Select: M102: MongoDB for DBAs
? Found 8 Lists. Select: Chapter 1: Introduction
> Searching Courseware [====================] 100%
i Could not locate any videos.

**Comment by przemyslawpluta** [comment]
Can'r replicate. Just tried the same against `M102: MongoDB for DBAs` and I can see `29 videos listed`.

**Comment by mobikenllc** [comment]
Install NPM: 1. C:\Users\Wilkenson> npm install mongo-edu 2. C:\Users\Wilkenson> npm install mongo-edu -g

Download Videos on Windows 8.1 Pro Command Prompt Window: C:\Users\Wilkenson\AppData\npm> mongo-edu --cw --cc --hq --co -d /videos/chapter1/

Download Handouts on Windows 8.1 Pro Command Prompt Window: C:\Users\Wilkenson\AppData\npm> mongo-edu -d /handouts/chapter1/ -h

Note: Your videos and handouts will be located at C:/videos/chapter1 C:/handouts/chapter1 respectively

Download Videos on Mac OS X Terminal: $ Mongo-edu --cw --cc --hq --co -d /usr/local/lib/videos/.

Download Handouts on Mac OS X Terminal: $ Mongo-edu -d /usr/local/lib/handouts/ -h.

Note: You must create both videos and handouts folders under /usr/local/lib/

**Comment by przemyslawpluta** [comment]
> @mobikenllc Note: You must create both videos and handouts folders under /usr/local/lib/

There is no need to create download directories as they will be created automatically if they don't exist.

**Comment by ravimohankaivar** [comment]
Hi.. Sorry to bother you again..

I am trying to download the course videos, but again getting the same message
"could not locate any videos".

Sorry... This issue was closed.. I am writing after a long time.. Please help..
If I cannot download in this way, can you please suggest me a link where I can directly download the videos of the below courses.

M102
M202
M101P

Below are the screenshots of how I tried to download.

![course_selection](https://cloud.githubusercontent.com/assets/12712723/9025871/880bfddc-3935-11e5-8a0d-125e01441f8c.jpg)
![list_selection](https://cloud.githubusercontent.com/assets/12712723/9025872/96e484c8-3935-11e5-917b-89273b612835.jpg)
![error_message](https://cloud.githubusercontent.com/assets/12712723/9025873/9cbd8d40-3935-11e5-87c4-856193031fc5.jpg)

Thank you...

**Comment by przemyslawpluta** [comment]
@ravimohankaivar just tested with `mongo-edu 0.2.14` against `M102`, `M202` and `M101P` and I can list and download all the courses without any issues. Try to upgrade to the latest version and let me know.

**Comment by ravimohankaivar** [comment]
I installed new version of mongo-edu (0.2.15), but still getting the same error message.

![mongo-edu-1](https://cloud.githubusercontent.com/assets/12712723/9044827/ddf11e8c-3a3c-11e5-9326-9b8e86538b91.jpg)

Please help.

**Comment by przemyslawpluta** [comment]
Can you connect to `youtube`? Are you connecting from your home or work network? This looks like network issue.

**Comment by ravimohankaivar** [comment]
Yes. I am able to connect to youtube and watch videos. I am connecting from my home. There is no network problem from my end. Still I am not able to download MongoDB videos.

**Comment by przemyslawpluta** [comment]
@ravimohankaivar try to reinstall python.

**Comment by ravimohankaivar** [comment]
On a different PC, I installed Python and NODE.JS freshly, and tried. But still I am getting the same message as "[could not locate any videos]"

**Comment by przemyslawpluta** [comment]
@ravimohankaivar upgrade to the latest version `mongo-edu 0.2.16` and let me know ...

**Comment by ravimohankaivar** [comment]
It worked! Thanks a lot...
I upgraded mongo-edu to 0.2.18 and it's working...
Thanks for the help. This is very useful for me.

What went wrong in the previous versions? Was it related to downloading from youtube?

**Comment by przemyslawpluta** [comment]
Cool.
