### ISSUE TITLE
Download terminates with --hq if "requested format not available"

### ISSUE THREAD

**Issue by MoJeeza** [przemyslawpluta/mongo-edu#47]
I seem to be having issues downloading - there are no errors.
After entering the email and password all I get is:
[>] Searching [============] 100%

and nothing.

It has worked in the past. Only thing i can think of is may be because I'm enrolled in two courses at the same time - which are currently in progress!!!!

I did re-install npm and mongo-edu.

**Comment by MoJeeza** [comment]
Ok, this issue can be closed...today it's working fine...although the failure rate is quite high and I have to keep trying again, but at least it's allowing me to download.

**Comment by przemyslawpluta** [comment]
High failure rate seems to be more related with your network then package itself. I can't replicate on my side.

**Comment by MoJeeza** [comment]
I figured out the casue - when I request --hq (high qualty videos) and if one of them is not - then it aborts at that point - with something like "requested format not available". All further downloads on that request are also terminated.

So for that specific video I just download the normal video.

It would be a good mod to overcome this issue !!

thanks for your follow up.

Mohsin

**Comment by przemyslawpluta** [comment]
Cool. Will have a look at this when I have a second.

**Comment by MoJeeza** [comment]
tkx..

**Comment by przemyslawpluta** [comment]
@MoJeeza which courses cased you issues?

**Comment by przemyslawpluta** [comment]
Should be ready now just upgrade to latest version `0.2.14`.

**Comment by MoJeeza** [comment]
Thanks a lot. Sorry for my late reply. I face the issue with the M202 course - where one video was of lower quality. It took me a while to realize the source/cause of the error.

thanks for taking care of it.

Kind regards,
Mohsin

**Comment by MoJeeza** [comment]
Just encountered this...FYI.

 [ MONGO-EDU 0.2.14 ]

desi@ud1204:/1TbA/m102-2/course$ mongo-edu -d /1TbA/m102-2/course/ -u <my_userID> --co --hq --cw

? MongoDB Uni User Name: <my_userID>
? MongoDB Uni Password: *********
> Searching [====================] 100%
? Found 5 Courses. Select: M102: MongoDB for DBAs
? Found 8 Lists. Select: Final Exam
> Searching Courseware [====================] 100%
> Collecting [====================] 100%
? Select From 21 Videos. Download: All
Error: Command failed: WARNING: Could not send HEAD request to https://youtu.be/20:02:22.656Z: HTTP Error 404: Not Found
ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
desi@ud120
