### ISSUE TITLE
Self signed certificate issue

### ISSUE THREAD

**Issue by farscapeone** [przemyslawpluta/mongo-edu#48]
I am running mongo-edu within a corporate environment.  YouTube is accessible.  I have installed NodeJS with NPM support and have installed the latest version of mongo-edu. 

I am getting a "Self signed certificate" error when I attempt to run the command - see below 

Please help

----------------------------------------------------------------------

$ mongo-edu -d .

 [ MONGO-EDU 0.2.14 ]

? MongoDB Uni User Name: XXXXXX@gmail.com
? MongoDB Uni Password: *********
C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\mongo-edu\lib\initialize.js:26
            if (err !== null) { throw err; }
                                      ^
Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

**Comment by przemyslawpluta** [comment]
What version of `py` have you got installed? Also have you tired running it with `-ncc`?

**Comment by farscapeone** [comment]
$ python --version
Python 2.7.8

Have tried the following with error as well:  mongo-edu -d . --ncc

**Comment by przemyslawpluta** [comment]
Tried that same on my side and can't replicate the issue you're having. I'd suggest reinstalling `py` ... let me know.

**Comment by farscapeone** [comment]
Just found out that is most likely internal firewall/proxy causing problems - will close the issue.  Thanks for help
