### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by lkurylo** [przemyslawpluta/mongo-edu#49]
I tried to download videos for the M101N course and I got the error:

Error: spawn ENOENT
at errnoException (child_process.js:1001:11)
at Process.ChildProcess._handle.onexit (child_process.js:792:34)

In one of the other issues here I have found that, the problem can be the missing python executable in the PATH, but it doesn't look that's the case this time:

C:\Users\lkurylo>python -V
Python 2.7.6
C:\Users\lkurylo>node -v
v0.10.31

Any other ideas?

**Comment by przemyslawpluta** [comment]
Can't replicate. Can you post entire output of `mongo-edu`.

**Comment by lkurylo** [comment]
That's all I can get: 
![mongoedu](https://cloud.githubusercontent.com/assets/744244/8716487/fc0c4982-2b91-11e5-9f58-680f66245277.png)

**Comment by przemyslawpluta** [comment]
It looks like an issue with the `python` installation. Please try to reinstall it.

**Comment by przemyslawpluta** [comment]
`mongo-edu` would complain if it could not find `python` executable with:

```
Can't find Python executable python. Check if Python installed ... if so set the PYTHON env variable.
```

as it's not complaining in this case executable has been located. Try to reinstall `python`.

**Comment by lkurylo** [comment]
Yes, now it works properly.
Thank you.
