### ISSUE TITLE
npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by yhw82** [przemyslawpluta/mongo-edu#50]
MongoDB Developer course is just started.

I'm trying to download videos using mongo-edu using the following command:

>mongo-edu -d /videos/ 
>MongoDB username: <entered>
>MongoDB passowrd: <entered>
>searching.......[100%]

Program exits after the above line. 

I did use this tool last year to download other videos in MongoDB but it doesn't work now for the new course. Are the videos available in mongo-edu?

**Comment by przemyslawpluta** [comment]
add `--cw`

**Comment by yhw82** [comment]
mongo-edu -d /videos/ --cw command does the same thing...no difference.
It exits the mongo-edu after searching 100%. Any idea how I can resolve this?

**Comment by przemyslawpluta** [comment]
Try to reinstall python.

**Comment by przemyslawpluta** [comment]
@yhw82 upgrade to the latest version `mongo-edu 0.2.16` and let me know ...

**Comment by yhw82** [comment]
How do I upgrade mongo-edu?

Should I run the following commands?
npm uninstall mongo-edu -g
npm install mongo-edu -g

**Comment by przemyslawpluta** [comment]
@yhw82 yes

**Comment by yhw82** [comment]
Reinstalled the mongo-edu using the above commands but the issue is no different. What else I can try?

**Comment by przemyslawpluta** [comment]
@yhw82 can you post the full snapshot of the console output.

**Comment by przemyslawpluta** [comment]
OK. @yhw82 try latest version `mongo-edu 0.2.17`.

**Comment by yhw82** [comment]
![image](https://cloud.githubusercontent.com/assets/8198759/9126119/94b3192a-3cec-11e5-85a6-e1f8101b385d.png)

nodeJ version is v0.10.29
npm version is v1.4.14
Python version (Canopy distribution) is 2.7.6
 
How do I check the mongo-edu version? Would reinstallation give me v0.2.17?

**Comment by przemyslawpluta** [comment]
`npm uninstall mongo-edu -g` then `npm install mongo-edu -g`

**Comment by ash611w** [comment]
I am getting list of errors while installing mongo-edu. I am using Linux-Ubuntu-14.04 LTS.

Error: ENOENT, chown '/usr/local/lib/node_modules/mongo-edu/node_modules/colors/themes'

 Error: ENOENT, lstat '/usr/local/lib/node_modules/mongo-edu/node_modules/request-progress/node_modules/throttleit/Readme.md'

 Error: ENOENT, lstat '/usr/local/lib/node_modules/mongo-edu/node_modules/mv/node_modules/ncp/.travis.yml'

**Comment by yhw82** [comment]
I've uninstalled and then reinstalled the mongo-edu...but it seems it's installing v0.1.24....don't know why... the issue still occurs after reinstallation

![image](https://cloud.githubusercontent.com/assets/8198759/9147331/da15c082-3da8-11e5-9340-2715a83dda1d.png)

**Comment by przemyslawpluta** [comment]
Try `npm install mongo-edu@0.2.18 -g`

**Comment by yhw82** [comment]
I could not install the version using the command you've mentioned.

![image](https://cloud.githubusercontent.com/assets/8198759/9148038/5d297e7c-3db4-11e5-9191-bba12e8ad578.png)

**Comment by przemyslawpluta** [comment]
It looks like you have issues with `npm` itself. What do you get when you run `npm view mongo-edu versions`?

**Comment by yhw82** [comment]
When I ran the command, it shows the version as 0.1.24.
How can I successfully remove npm and install the correct mongo-edu version?

**Comment by przemyslawpluta** [comment]
Just uninstall nodejs ... then install latest 0.10.x or 0.12.x nodejs from the website.

**Comment by yhw82** [comment]
I installed the latest node.js and retried the mongo-edu installation and I'm getting the following error.
I have no proxy enabled in any of my web browers but I am having socket connection error:

![image](https://cloud.githubusercontent.com/assets/8198759/9152961/667b5dfa-3e82-11e5-975c-7f38d805d00d.png)

**Comment by przemyslawpluta** [comment]
Looks like you have `network / npm issues`. What do you get whan you run `npm config get proxy`? If there is no proxy setup you should get `null` or `err`. Check if you have environment variable `HTTP_PROXY`. Can you access `URLs` from your brower?

**Comment by yhw82** [comment]
I've managed to connect to mongo-edu after removing the proxy.....but getting other errors as such:
any idea what the problem is? I'm losing the connection after downloading a video clip..
![image](https://cloud.githubusercontent.com/assets/8198759/9154128/fea4019e-3ec4-11e5-80a0-f8343dbd0cc1.png)

**Comment by przemyslawpluta** [comment]
What is the output of:

```bash
python %HOMEPATH%\AppData\Roaming\npm\node_modules\mongo-edu\node_modules\youtube-dl\bin\youtube-dl YQTqdLe3W4M --verbose`
```

**Comment by przemyslawpluta** [comment]
@yhw82 shall I assume you got it sorted?

**Comment by przemyslawpluta** [comment]
Closing for now ... will reopen if later if required.
