### ISSUE TITLE
Errors while installing mongo-edu

### ISSUE THREAD

**Issue by ash611w** [przemyslawpluta/mongo-edu#52]
Using Linux-Ubuntu14.04LTS-
Error: ENOENT, chown '/usr/local/lib/node_modules/mongo-edu/node_modules/colors/themes'

 Error: ENOENT, lstat '/usr/local/lib/node_modules/mongo-edu/node_modules/request-progress/node_modules/throttleit/Readme.md'

 Error: ENOENT, lstat '/usr/local/lib/node_modules/mongo-edu/node_modules/mv/node_modules/ncp/.travis.yml'

**Comment by przemyslawpluta** [comment]
Can you attach the whole screenshot.

**Comment by ash611w** [comment]
![Uploading Screenshot from 2015-08-08 03:58:41.png…]()
![screenshot from 2015-08-08 03 58 52](https://cloud.githubusercontent.com/assets/9897700/9147511/a5069ef2-3d85-11e5-8796-39f0d7e6014d.png)
![Uploading Screenshot from 2015-08-08 03:59:16.png…]()
![Uploading Screenshot from 2015-08-08 03:59:27.png…]()

**Comment by ash611w** [comment]
![screenshot from 2015-08-08 03 58 41](https://cloud.githubusercontent.com/assets/9897700/9147525/c3735d76-3d85-11e5-831d-755334f95ab3.png)

**Comment by ash611w** [comment]
![screenshot from 2015-08-08 03 59 16](https://cloud.githubusercontent.com/assets/9897700/9147534/d4333ea6-3d85-11e5-8129-7027c0b0f0e2.png)

**Comment by ash611w** [comment]
![screenshot from 2015-08-08 03 59 27](https://cloud.githubusercontent.com/assets/9897700/9147539/e27fbc82-3d85-11e5-94a8-1bf7ea7e224f.png)

**Comment by przemyslawpluta** [comment]
Try `npm cache clean` then `npm install mongo-edu -g`.

**Comment by ash611w** [comment]
Sir, I found that the other person was also facing the same problem I tried one of your answer to install nodejs-legacy by writing this in terminal-sudo apt-get install nodejs-legacy. andit worked. The videos downloading. Thanks alot Sir.

**Comment by przemyslawpluta** [comment]
https://github.com/przemyslawpluta/mongo-edu/issues/36
