### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by kkoci** [przemyslawpluta/mongo-edu#53]
Hi, this was working yesterday, I'm on debian wheezy, this what a I get now:

user@debian:~/mongo_edu$ npm install mongo_edu -g
npm ERR! 404 Not Found
npm ERR! not ok code 0

Is it me? or a momentary connection error?

**Comment by przemyslawpluta** [comment]
```js
npm install mongo-edu -g
```

**Comment by kkoci** [comment]
LoL, my bad, thank you very much
