### ISSUE TITLE
Error starting the app on Win7

### ISSUE THREAD

**Issue by LyannaTarg** [przemyslawpluta/mongo-edu#54]
Hi,
i try to start the mongo-edu application from my pc that runs Win7 Pro.
This is what i see (sorry it is in Italian but i will give you a translation):
C:\Users\temp>mongo-edu
"mongo-edu" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
(Eng: "mongo-edu" is not recognized as an internal command or an external one, an executable program or a batch file)

So i tried to go in the directory: C:\Users\temp\node_modules\mongo-edu
and there i have a bigger issue:
![windows script host](https://cloud.githubusercontent.com/assets/13886020/9382268/825940bc-473f-11e5-8a8e-2efc86dd7483.png)
Riga = Row
Carattere = Character
Errore = Error
Previsto oggetto = Object expected
Codice = Code
Origine = Origin
Errore di run-time di Microsoft JScript = Microsoft JScript run-time error

I had no issues when i installed it on my virtual machine that is a debian 8...

Do i have to set some environment parameters? or something else?

**Comment by przemyslawpluta** [comment]
It looks like you've installed `mongo-edu` as local installation via `npm install mongo-edu` in this case if you want to start it you have to locate your installation ( looks like `C:\Users\temp\node_modules\mongo-edu` ) and then from within the directory run `node ./bin/mongo-edu [options]`.

Preferable option is to install it globally via `npm install mongo-edu -g` then you can just run `mongo-edu [options]` from any location.

**Comment by LyannaTarg** [comment]
aaaaaaaah ok now i understand!

Thanks a lot! I will install it globally!
