### ISSUE TITLE
How can I download mongodb 101j course videos?

### ISSUE THREAD

**Issue by abdulqudoos** [przemyslawpluta/mongo-edu#56]
I am from pakistan and here youtube is block, so I am facing problems to download videos even through direct download or by using node,I am playing videos by using zenmate,   youtube download link is not work in IDM, its like private video link not work on proxy in IDM.
And in Kaltura video player no download option comes.
Is there any other platform from where I download load mongodb java course videos?

**Comment by przemyslawpluta** [comment]
@abdulqudoos try to ask the question on https://university.mongodb.com/
