### ISSUE TITLE
Not Downloading all Videos.

### ISSUE THREAD

**Issue by arashpath** [przemyslawpluta/mongo-edu#57]
In Mongo M202 Oct 2015 Course 
Video for following topics  are not getting downloaded.
-  Reference numbers for disaster recovery & Quiz
-  Downtime tolerance matrix & Quiz
- Systems with low tolerance for downtime and data loss & Quiz
- Can I address downtime and data loss with just 2 nodes? & Quiz
- Meeting downtime and data loss requirements
- Considering capacity with downtime and data loss addressed 

Only 24 videos are downloaded.

Thanks for the gr8 work

**Comment by przemyslawpluta** [comment]
Just tested agains `M202` and downloaded all available videos in the course without any issues.

**Comment by RacerEvan55** [comment]
Same issue here.  On m101n it is not downloading all videos.  For example it skips the first 2 segments CRUD and the Mongo Shell  and Secrets of the Mongo Shell  and goes straight to Intro to BSON.

**Comment by przemyslawpluta** [comment]
@arashpath @RacerEvan55 what OS are you on?

**Comment by RacerEvan55** [comment]
Windows 10
latest version of node
python 3.4.3 

I kicked off a download again this morning,  will report back tonight to see if it worked this time.

**Comment by RacerEvan55** [comment]
looks like it is intermittent, and where the code builds the list of youtube videos (not the actual downloading part)
I just tried it with M102 week 2.  First time I ran it, it found 9 videos.  2nd and 3rd times 23 videos.

**Comment by arashpath** [comment]
Yes it is intermediate. 
Can be avoided if we login via website and attempt to play some videos before downloading all. 
Else it will skip videos from 2nd to 5th.

**Comment by przemyslawpluta** [comment]
@arashpath are you referencing M102?

**Comment by przemyslawpluta** [comment]
Pushed new version to npm with a slight change to the streams `mongo-edu v0.2.22 `.

Video lists depend on the responses from the mongodb servers so if there is no response for the particular webpage or webpage response is partial there is nothing to list hence on odd occasions you get different video count.

I run 10x separate tests on `OSX`, `win7` and `win8` and have seen this count issue happening once.

BTW what is your [broadband speed](http://www.speedtest.net/)?
