### ISSUE TITLE
Handout download not working.  DLing html file instead

### ISSUE THREAD

**Issue by RacerEvan55** [przemyslawpluta/mongo-edu#59]
running either
mongo-edu -d E:\m101N\m101n_week1h -h
mongo-edu -d E:\m101N\m101n_week1h -h --uz

downloads a 22kb file with no extension (html) for each week  
see attached for example

[52a9fa01e2d423242df5901c.txt](https://github.com/przemyslawpluta/mongo-edu/files/42876/52a9fa01e2d423242df5901c.txt)

**Comment by przemyslawpluta** [comment]
@RacerEvan55 sorted upgrade to latest version.
