### ISSUE TITLE
isn't finding any registered courses

### ISSUE THREAD

**Issue by grendelson** [przemyslawpluta/mongo-edu#60]
Using Windows 7 with brand new install:

PS C:\Users\jneff\Downloads\MONGOVIDS> node -v
v5.1.0
PS C:\Users\jneff\Downloads\MONGOVIDS> npm -v
3.3.12
PS C:\Users\jneff\Downloads\MONGOVIDS> python -V
Python 3.5.0
PS C:\Users\jneff\Downloads\MONGOVIDS> mongo-edu --help

 [ MONGO-EDU 0.2.25 ]

When I use "mongo-edu -d c:\videos -u <email> --cw --cc --co --hq --save myvideo" I get prompted for password and after a search it tells me no classes found 
"Hi John. Could not locate any courses in your profile. Have you registered already?"

Is it the version or is there a bug?  I DO have a course I'm registered for M102 through Dec 8.

**Comment by przemyslawpluta** [comment]
This has been fixed now. Unfortunately there are some issues with `npm publishing` so I can't publish into `npm` latest version.

At the moment you can `npm install przemyslawpluta/mongo-edu -g`
