### ISSUE TITLE
Fedora 23 - Could not locate any courses

### ISSUE THREAD

**Issue by tkontogi** [przemyslawpluta/mongo-edu#61]
Hi All,

On F23 I get the following error:

[ MONGO-EDU 0.2.25 ]

? MongoDB Uni User Name *****@********.com
? MongoDB Uni Password ********
> Searching [====================] 100%
i Hi Theo 😄  Could not locate any courses in your profile. Have you registered already?

**Comment by przemyslawpluta** [comment]
Same as https://github.com/przemyslawpluta/mongo-edu/issues/60
