### ISSUE TITLE
not able to download videos after completion of coursers

### ISSUE THREAD

**Issue by sbasani** [przemyslawpluta/mongo-edu#62]
I have completed M102 AND M202 in Dec. when I tried to down load videos I am getting following error

Looks like you haven't registered for any courses yet at https://university.mongodb.com/courses/catalog.

**Comment by przemyslawpluta** [comment]
@sbasani done - now you can download videos for `current` and `completed` courses. Just upgrade to latest version `mongo-edu v0.2.31`.

**Comment by sbasani** [comment]
Thank you, I am able to download completed course videos.
