### ISSUE TITLE
Resume downloads of list when network drops

### ISSUE THREAD

**Issue by seanmavley** [przemyslawpluta/mongo-edu#63]
I'm on an unstable network. During downloads, after 10 or so videos downloaded, it stops. Can I resume the download from the last uncompleted file?

Is that what the load/save preset is for?

Or better still, a way to retry downloading when network drops? I get this error when it cuts:

Error: getaddrinfo EAI_AGAIN r17---sn-aigllnsy.googlevideo.com:443
    at Object.exports._errnoException (util.js:855:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

The network is fast enough, just unstable, comes and goes like a ghost

At the moment, I can't use it because every time it stops, I need to restart from scratch, and I wished I was an ISP

**Comment by przemyslawpluta** [comment]
@seanmavley will deploy something tomorrow to `npm`. Enhancement will resume the download of the videos. It should help out with your network issues.

**Comment by seanmavley** [comment]
Thanks. Will be a great addition.

**Comment by przemyslawpluta** [comment]
@seanmavley in reality you might still get the same error msg but next download will start from the place you've left off hence you don't have to download entire file all over again.

**Comment by seanmavley** [comment]
That's even better. So, say, if I'm downloading 10 videos in a course, five
succeeds before error, then on next re download, it begins download from
the 6th file in line, when it learns 1 to 5 files are already in the
directory.

**Comment by przemyslawpluta** [comment]
@seanmavley done. Just upgrade to latest version `mongo-edu v0.2.40`.

**Comment by seanmavley** [comment]
Works Great. Awesome! Thanks
