### ISSUE TITLE
Retry attempts - Download gives up too quickly

### ISSUE THREAD

**Issue by seanmavley** [przemyslawpluta/mongo-edu#64]
Really appreciate the resume download thing. Priceless!

However, I think the downloader gives up too quickly when it tries and can't get connection. 

An optional parameter, like, `mongo-edu -d . --retry 10` will be great.

I wouldn't mind setting my retries to 5 Million. Over 2 hours now, trying to download a course. Although it downloads fast enough, its unstable, and I have to be checking if it's ongoing or stopped

**Comment by przemyslawpluta** [comment]
What's the error you're getting?

**Comment by seanmavley** [comment]
That's the error. It appears to download from 433 instead of 80, so perhaps SSL things to causing drops in connection?

cursors introduction-XzNqJpImCP4.mp4. Done in: 29469.104ms
i 8 left ...
Error: getaddrinfo EAI_AGAIN r20---sn-4g57knzk.googlevideo.com:443
    at Object.exports._errnoException (util.js:856:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)

**Comment by przemyslawpluta** [comment]
@seanmavley please post entire mongo-edu output from the beginning.

**Comment by seanmavley** [comment]
Please, here is it, the entire output for downloading the course: 

http://pastebin.com/6uT0wjVj

thanks

**Comment by przemyslawpluta** [comment]
@seanmavley try latest version with addition of `--retry timeInSeconds`. It's not on the `npm` yet so install it directly from git repo `npm install przemyslawpluta/mongo-edu` and let me know.

`timeInSeconds` indicates amount of time it will retry to download if case of issues.

**Comment by seanmavley** [comment]
okay, I'm about to install. will let you know how it goes.

**Comment by seanmavley** [comment]
I tried it, and it didn't drop. Download continued till the end in peace. If it retries behind the scenes without any output in terminal to indicate its retrying, then that's amazing. It doesn't need to show a visual output, as long as it works perfectly behind the scenes with the `--retry ` set.

With this added @przemyslawpluta , how about by default, a retry of say, 3 or 5?

**Comment by przemyslawpluta** [comment]
@seanmavley good to hear it. Yes it's all happening internally hence no info printed in the console don't think it's neccesery. Was thinking about default `--retry` value and probably will push it in the `npm` release. Thanks for testing.

**Comment by seanmavley** [comment]
It's such an amazing tool and saves time a lot. Thanks for the tool.
