### ISSUE TITLE
mongo-edu download issue

### ISSUE THREAD

**Issue by datapassion1** [przemyslawpluta/mongo-edu#65]
? MongoDB Uni Password **********
> Searching [====================] 100%
? Select Courses: Current
? Hi Dileep. Found 4 Courses. Select: M102: MongoDB for DBAs
? Found 1 List. Select: Chapter 1: Introduction
> Searching Courseware [====================] 100%
C:\Users\dtarigopula\AppData\Roaming\npm\node_modules\mongo-edu\lib\videos.js:29
2
                    hash[item] = info._filename;
                                     ^

TypeError: Cannot read property '_filename' of undefined
    at C:\Users\dtarigopula\AppData\Roaming\npm\node_modules\mongo-edu\lib\video
s.js:292:38
    at C:\Users\dtarigopula\AppData\Roaming\npm\node_modules\mongo-edu\node_modu
les\youtube-dl\lib\youtube-dl.js:243:21
    at C:\Users\dtarigopula\AppData\Roaming\npm\node_modules\mongo-edu\node_modu
les\youtube-dl\lib\youtube-dl.js:151:21
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by przemyslawpluta** [comment]
@datapassion1 how frequently do you see this issue? Is it happening every time as I can't replicate this after running multiple tests.

**Comment by datapassion1** [comment]
I see the issue every time, I have tried these commands :    
C:\>mongo-edu -d /videos/
C:\>mongo-edu -d C:\Users\dtarigopula\Desktop\Career\MongoDB\M102 - MongoDB for
DBAs expgrad@gmail.com --cw --hq -cc

**Comment by przemyslawpluta** [comment]
@datapassion1 try latest version. It's not on the `npm` yet so install it directly from git repo `npm install przemyslawpluta/mongo-edu -g` and let me know.

**Comment by datapassion1** [comment]
can you please clarify in more details. how to install from git repository ? what's the link for the git repo ?

**Comment by przemyslawpluta** [comment]
`npm install przemyslawpluta/mongo-edu -g`

**Comment by datapassion1** [comment]
I have executed this on c drive root directory...got error below

C:\>npm install przemyslawpluta/mongo-edu -g
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:82:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  przemyslawpluta/mongo-edu resetting remote C:\Users\dtari
gopula\AppData\Roaming\npm-cache\_git-remotes\git-github-com-przemyslawpluta-mon
go-edu-git-38208a978f12d8f5edeb7ee4e658cca9 because of error: { [Error: not foun
d: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\dtarigopula\AppData\Roaming\npm-cache\_gi
t-remotes\_templates --mirror git://github.com/przemyslawpluta/mongo-edu.git C:\
Users\dtarigopula\AppData\Roaming\npm-cache\_git-remotes\git-github-com-przemysl
awpluta-mongo-edu-git-38208a978f12d8f5edeb7ee4e658cca9: undefined
npm ERR! git clone --template=C:\Users\dtarigopula\AppData\Roaming\npm-cache\_gi
t-remotes\_templates --mirror git://github.com/przemyslawpluta/mongo-edu.git C:\
Users\dtarigopula\AppData\Roaming\npm-cache\_git-remotes\git-github-com-przemysl
awpluta-mongo-edu-git-38208a978f12d8f5edeb7ee4e658cca9: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:82:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  przemyslawpluta/mongo-edu resetting remote C:\Users\dtari
gopula\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-przemyslawplu
ta-mongo-edu-git-acc0b3fe656459a8fdc68affeb91f247 because of error: { [Error: no
t found: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\dtarigopula\AppData\Roaming\npm-cache\_gi
t-remotes\_templates --mirror https://github.com/przemyslawpluta/mongo-edu.git C
:\Users\dtarigopula\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-
przemyslawpluta-mongo-edu-git-acc0b3fe656459a8fdc68affeb91f247: undefined
npm ERR! git clone --template=C:\Users\dtarigopula\AppData\Roaming\npm-cache\_gi
t-remotes\_templates --mirror https://github.com/przemyslawpluta/mongo-edu.git C
:\Users\dtarigopula\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-
przemyslawpluta-mongo-edu-git-acc0b3fe656459a8fdc68affeb91f247: undefined
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:78:19)
npm WARN addRemoteGit     at E (C:\Program Files\nodejs\node_modules\npm\node_mo
dules\which\which.js:82:29)
npm WARN addRemoteGit     at C:\Program Files\nodejs\node_modules\npm\node_modul
es\which\which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  przemyslawpluta/mongo-edu resetting remote C:\Users\dtari
gopula\AppData\Roaming\npm-cache\_git-remotes\git-github-com-przemyslawpluta-mon
go-edu-git-306d00b0fabefe9f6a8602f56fbab458 because of error: { [Error: not foun
d: git] code: 'ENOGIT' }
npm ERR! git clone --template=C:\Users\dtarigopula\AppData\Roaming\npm-cache\_gi
t-remotes\_templates --mirror git@github.com:przemyslawpluta/mongo-edu.git C:\Us
ers\dtarigopula\AppData\Roaming\npm-cache\_git-remotes\git-github-com-przemyslaw
pluta-mongo-edu-git-306d00b0fabefe9f6a8602f56fbab458: undefined
npm ERR! git clone --template=C:\Users\dtarigopula\AppData\Roaming\npm-cache\_gi
t-remotes\_templates --mirror git@github.com:przemyslawpluta/mongo-edu.git C:\Us
ers\dtarigopula\AppData\Roaming\npm-cache\_git-remotes\git-github-com-przemyslaw
pluta-mongo-edu-git-306d00b0fabefe9f6a8602f56fbab458: undefined
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "przemyslawpluta/mongo-edu" "-g"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "przemyslawpluta/mongo-edu" "-g"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! path C:\npm-debug.log.5ef18612bc59ef53af9a1967a06d63d8
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\npm-debug.log.5ef18612b
c59ef53af9a1967a06d63d8'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\npm-debug.log.5ef18
612bc59ef53af9a1967a06d63d8']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\npm-debug.log.5ef18612bc59ef53af9a1967a06d63d8' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

C:\>

**Comment by datapassion1** [comment]
installed versions are 
C:\>node -v
v5.4.0

C:\>npm -v
3.3.12

C:\>python -V
Python 3.4.4

**Comment by przemyslawpluta** [comment]
@datapassion1 you don't have git installed.

You have two options either install [git](https://desktop.github.com/) then use `git bash` to install directly from repo with `npm install przemyslawpluta/mongo-edu -g`

or

just download [zipped branch](https://github.com/przemyslawpluta/mongo-edu/archive/master.zip) directly to your desktop, unzip then in root directory run `npm install` and after:

```bash
node ./bin/mongo-edu -d "C:\Users\dtarigopula\Desktop\Career\MongoDB\M102 - MongoDB for
DBAs" -u expgrad@gmail.com --cw --hq -cc
```

**Comment by datapassion1** [comment]
GITHUB error : ? Hi Dileep. Found 4 Courses. Select: M202: MongoDB Advanced Deployment and Ope
i Unable to locate any videos lists in the wiki. Are videos list present?
? Default wiki search returned no resuts. Perform courseware search with --cw ?
 (Y/n) y
? Default wiki search returned no resuts. Perform courseware search with --cw ?
 Yes
? Found 1 List. Select: Chapter 1: System Sizing and Tuning

? Select From 48 Videos. Download: All
i Download Failed: Error: Command failed: python C:\Users\dtarigopula\AppData\Roaming\npm\node_modules\mongo-edu\node_modules\youtube-dl\bin\youtube-dl --dump-json --format=18 https://youtu.be/MnZrqOfei4g
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

--------------------------------------
I tried the zipped folder option also...good thing is I moved one step ahead..It showed list of videos..but when I selected for download got the error below

C:\Users\dtarigopula\Desktop\Career\MongoDB\Installation files\mongo-edu-master\
mongo-edu-master>node ./bin/mongo-edu -d /videos/


 [ MONGO-EDU 0.2.52 ]


? MongoDB Uni User Name expgrad@gmail.com
? MongoDB Uni Password **********
> Searching [====================] 100%
? Select Courses: Current
? Hi Dileep. Found 4 Courses. Select: M101J: MongoDB for Java Developers
i Unable to locate any videos lists in the wiki. Are videos list present?
? Default wiki search returned no resuts. Perform courseware search with --cw ?
 Yes
? Found 1 List. Select: Week 1: Introduction
> Searching Courseware [====================] 100%
> Collecting [====================] 100%
? Select From 33 Videos. Download: All
i Download Failed: Error: Command failed: python C:\Users\dtarigopula\Desktop\Ca
reer\MongoDB\Installation files\mongo-edu-master\mongo-edu-master\node_modules\y
outube-dl\bin\youtube-dl --dump-json --format=18 https://youtu.be/kTIqocKMItU
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILE
D] certificate verify failed (_ssl.c:600)> (caused by URLError(SSLError(1, '[SSL
: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by przemyslawpluta** [comment]
@datapassion1 looks like https://github.com/przemyslawpluta/mongo-edu/issues/2

**Comment by datapassion1** [comment]
can you please explain step by step. what are the exact commands to be used ?

**Comment by sherbaz** [comment]
Hi datapassion1,
I got exactly the same error ".............Command failed: python C:\Users\Sherbaz...". I removed python 3.5 and installed legacy python 2.7 (https://www.python.org/ftp/python/2.7.11/python-2.7.11.msi).

**Comment by przemyslawpluta** [comment]
@datapassion1 as @sherbaz described you can drop down a version of `python` or add `--ncc` flag as described in https://github.com/przemyslawpluta/mongo-edu/issues/2

```bash
node ./bin/mongo-edu -d "C:\Users\dtarigopula\Desktop\Career\MongoDB\M102 - MongoDB for
DBAs" -u expgrad@gmail.com --cw --hq --cc --ncc
```

New version `mongo-edu 0.2.52` is on npm now.

**Comment by przemyslawpluta** [comment]
@datapassion1 let me know if you're running fine.
