### ISSUE TITLE
Is it possible to pull the subtitles?

### ISSUE THREAD

**Issue by juancarlosfarah** [przemyslawpluta/mongo-edu#67]
Hi @przemyslawpluta. I had a feature request in mind and wanted to see if it would be possible for you to do. We've got some students asking for transcripts of the videos. Since a large number of students download the videos with mongo-edu, I was wondering how hard it would be to give them the option to pull the subtitles from each video and save them as a text file. It would be great if this would be possible. Kind regards and thanks again for mongo-edu!

**Comment by przemyslawpluta** [comment]
@juancarlosfarah just pass `--cc` and closed captions if available will be downloaded with the videos.

**Comment by juancarlosfarah** [comment]
@przemyslawpluta, awesome thanks!

**Comment by juancarlosfarah** [comment]
As an aside, is it possible to only download the captions and not the videos?

**Comment by przemyslawpluta** [comment]
@juancarlosfarah yes but that's a feature request.

**Comment by przemyslawpluta** [comment]
@juancarlosfarah just pushed new version to git. Give it a spin by installing directly via:
```bash
npm install przemyslawpluta/mongo-edu -g
```
then run it with `mongo-edu -u your-user-name -d download-path --cco`

**Comment by juancarlosfarah** [comment]
@przemyslawpluta thanks for that! I just tried it out and it looks that the caption files that are being pulled are the automated ones, not the ones we upload to YouTube. For example for the first lecture of M101P, the file I downloaded with mongo-edu starts "welcome to M one on one Mongo dB for developers", while the captions on YouTube start "Welcome to 101 MongoDB for Developers." Is there any way of pulling the *official* subtitles? Thanks again for doing this!

**Comment by przemyslawpluta** [comment]
@juancarlosfarah can you post a link to that video.

**Comment by juancarlosfarah** [comment]
@przemyslawpluta FYI, here is the link to that video: https://www.youtube.com/watch?v=D_OtQYRyPvE

**Comment by przemyslawpluta** [comment]
@juancarlosfarah done. Just install from git and give it a spin. It will download original subtitles by default if available if not fails to auto.

**Comment by juancarlosfarah** [comment]
@przemyslawpluta Awesome! Just tried it out and it works great. Thanks for
pushing that out so fast!

On 14 January 2016 at 19:46, Przemyslaw Pluta <notifications@github.com>
wrote:

> @juancarlosfarah <https://github.com/juancarlosfarah> done. Just install
> from git and give it a spin. It will download original subtitles by default
> if available if not fails to auto.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/przemyslawpluta/mongo-edu/issues/67#issuecomment-171735752>
> .
>



-- 
Juan Carlos Farah
E. farah.juancarlos@gmail.com
Skype. juancarlos.farah
Twitter. juancarlosfarah
www.juancarlosfarah.com
