### ISSUE TITLE
Problem when download video

### ISSUE THREAD

**Issue by ahmadmuiz** [przemyslawpluta/mongo-edu#68]
I have a problem when run this command 
AHMAD MUIZ L@AHMADMUIZ-PC ~
$ mongo-edu -d "/E/GitHub/Mongo University/M102/Week 3" --cw --co --cc --hq

 [ MONGO-EDU 0.2.51 ]

? MongoDB Uni User Name *********@gmail.com
? MongoDB Uni Password ***********
> Searching [====================] 100%
? Select Courses: Current
? Hi Ahmad Muiz. Found 3 Courses. Select: M102: MongoDB for DBAs
? Found 3 Lists. Select: Chapter 3: Performance
> Searching Courseware [====================] 100%
> Collecting [==============      ] 71%c:\Users\AHMAD MUIZ L\AppData\Roaming\npm
\node_modules\mongo-edu\lib\videos.js:292
                    hash[item] = info._filename;
                                     ^

TypeError: Cannot read property '_filename' of undefined
    at c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo-edu\lib\vide
os.js:292:38
    at c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo-edu\node_mod
ules\youtube-dl\lib\youtube-dl.js:243:21
    at c:\Users\AHMAD MUIZ L\AppData\Roaming\npm\node_modules\mongo-edu\node_mod
ules\youtube-dl\lib\youtube-dl.js:151:21
    at ChildProcess.exithandler (child_process.js:220:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

Any help would be appreciate. Thanks

**Comment by przemyslawpluta** [comment]
Same as https://github.com/przemyslawpluta/mongo-edu/issues/65
