### ISSUE TITLE
Regarding MongoDB class room videos to download error

### ISSUE THREAD

**Issue by prameshoviam** [przemyslawpluta/mongo-edu#69]
Hi..

Getting error on using the below command on downloading the Course videos..Pls help.

---------------------------
Windows Script Host
---------------------------
Script:	E:\MongoDB NodeJS\Course-HandOuts\mongo-edu-master\mongo-edu.js
Line:	9
Char:	1
Error:	Object expected
Code:	800A138F
Source: 	Microsoft JScript runtime error

---------------------------
OK   
---------------------------

**Comment by przemyslawpluta** [comment]
@prameshoviam looks like you're trying to run a script like a batch file. This is not the case here ... Please read the [Installation](https://github.com/przemyslawpluta/mongo-edu/wiki/Installation) for details.
