### ISSUE TITLE
Same issue as issue #39

### ISSUE THREAD

**Issue by cameronliam** [przemyslawpluta/mongo-edu#70]
Hi,
I am getting the same problem as in issue  #39, also downloading M101P. 
'Searching Courseware' runs quickly, but always hangs when it reaches ~%80 (min: 73%, max: 93%). Tried it on multiple networks, same result. Any advice?

OS X 10.10.5
Node v4.3.1

Example output:
> Searching [====================] 100%
? Select Courses: Completed
? Hi Liam 😄  Found 1 Course. Select: M101P: MongoDB for Developers
? Found 8 Lists. Select: Chapter 1: Introduction
> Searching Courseware [==                  ] 12%
> Searching Courseware [=======             ] 37%
> Searching Courseware [============        ] 61%
> Searching Courseware [================    ] 78%
> Searching Courseware [==================  ] 88%

**Comment by przemyslawpluta** [comment]
@cameronliam can't replicate tested multiple times without any issues based on versions you're describing.
