### ISSUE TITLE
Like issue #72

### ISSUE THREAD

**Issue by antvid** [przemyslawpluta/mongo-edu#73]
Like piotrv in #72 issue, I can't download the videos. Can you help me?. Thank you.

This is my command line:

C:\Users\a**_>mongo-edu -d "D:\Download" -u a**_@hotmail.com --cw --co --cc --hq --verbose

 [ MONGO-EDU 0.2.53 ]

? MongoDB Uni User Name a**_@hotmail.com
? MongoDB Uni Password ***_******

> Searching [====================] 100%
> ? Select Courses: Current
> ? Hi Antonio. Found 1 Course. Select: M102: MongoDB for DBAs
> i Unable to locate any videos lists in the wiki. Are videos list present?

**Comment by przemyslawpluta** [comment]
@antvid can't replicated just tested against latest version on _nix, mac os_ and win\* and I'm getting all the courses without any issues.

**Comment by antvid** [comment]
Well, @przemyslawpluta, I still have the problem. I'm doing the course and have all the videos available, but mongo-edu keeps giving the same message.

These are the current versions of the software I'm using under Windows 7:

C: > node -v
v4.4.2

C: > python -V
Python 3.5.1

Thank you!

**Comment by przemyslawpluta** [comment]
@antvid as with previous case it doesn't look like it's a mongo-edu issue so you have to chase this back with [mongodb university](https://university.mongodb.com/)

Worth setting up another account and testing on your side if it works with it.

**Comment by dsrini-open** [comment]
I am getting the same exception -
python updated to 3.4
npm using the 1.3.6
node v0.10
Cent OS 7 

Weird that it always seems to find videos in wiki, even if --cw option is present. 
""Unable to locate any videos lists in the wiki. Are videos list present?""

I see in the code - following div is looked for videos underneath - div.col-sm-9.course-content section
But, I am not getting course-content class , able to get to div.col-sm-9 not after that.

**Comment by przemyslawpluta** [comment]
@antvid @dsrini-open closing for now as it looks like it's a problem with accounts not mongo-edu. If more people report this issue will reopen if necessary.

**Comment by tropicloud** [comment]
mongo-edu is broken, it can't download videos.
it can download handouts, but no videos.

```
? Default wiki search returned no resuts. Perform courseware search with --cw ? Yes
i Unable to locate any videos lists in the wiki. Are videos list present?
```
