### ISSUE TITLE
Unable to locate any videos

### ISSUE THREAD

**Issue by tropicloud-2k** [przemyslawpluta/mongo-edu#74]
Something must have changed in MongoDB University, and, as a result, `mongo-edu` can't find any videos to download. It can still download handouts thought.

```
$ mongo-edu -d ~/videos

[ MONGO-EDU 0.2.53 ]

MongoDB Uni User Name ***********************
? MongoDB Uni Password ********
> Searching [====================] 100%
? Select Courses: Current
? Hi ********** 😄  Found 2 Courses. Select: M101JS: MongoDB for Node.js Developers
i Unable to locate any videos lists in the wiki. Are videos list present?
? Default wiki search returned no resuts. Perform courseware search with --cw ? Yes
i Unable to locate any videos lists in the wiki. Are videos list present?
```

**Comment by przemyslawpluta** [comment]
@tropicloud can't replicated just tested against latest version on _nix, mac os_ and win\* and I'm getting all the courses without any issues. This looks like same issue to https://github.com/przemyslawpluta/mongo-edu/issues/72 and https://github.com/przemyslawpluta/mongo-edu/issues/73

**Comment by tropicloud-2k** [comment]
Sorry, but it seems you are the only one who can use this tool. Maybe your are downloading completed courses. Have you tried to get current courses?

You can easily replicate this issue by spinning up a fresh Node.js droplet at DigitalOcean.

```
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Apr 29 08:05:13 EDT 2016

  System load: 0.0               Memory usage: 2%   Processes:       62
  Usage of /:  3.8% of 39.25GB   Swap usage:   0%   Users logged in: 0

  Graph this data and manage this system at:
    https://landscape.canonical.com/

root@node-2gb-nyc2-01:~# node -v
v4.4.3
root@node-2gb-nyc2-01:~# npm install mongo-edu -g

> youtube-dl@1.10.5 preinstall /usr/lib/node_modules/mongo-edu/node_modules/youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
Downloaded youtube-dl 2016.04.24
/usr/bin/mongo-edu -> /usr/lib/node_modules/mongo-edu/bin/mongo-edu

> mongo-edu@0.2.53 postinstall /usr/lib/node_modules/mongo-edu
> node ./.resume/deploy

Resume option for youtube-dl deployed

mongo-edu@0.2.53 /usr/lib/node_modules/mongo-edu
├── easy-table@1.0.0
├── get-youtube-id@1.0.0
├── progress@1.1.8
├── path-extra@3.0.0
├── filesize@3.1.6
├── colors@1.1.2
├── request-progress@1.0.2 (throttleit@1.0.0)
├── mv@2.1.1 (rimraf@2.4.5, ncp@2.0.0)
├── which@1.2.4 (isexe@1.1.2, is-absolute@0.1.7)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@6.0.4 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.3, inflight@1.0.4, minimatch@3.0.0)
├── rimraf@2.5.2 (glob@7.0.3)
├── yargs@3.31.0 (decamelize@1.2.0, y18n@3.2.1, camelcase@2.1.1, window-size@0.1.4, cliui@3.2.0, string-width@1.0.1, os-locale@1.4.0)
├── extract-zip@1.4.1 (debug@0.7.4, yauzl@2.4.1, mkdirp@0.5.0, concat-stream@1.5.0)
├── youtube-dl@1.10.5 (streamify@0.2.5)
├── request@2.67.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, node-uuid@1.4.7, qs@5.2.0, combined-stream@1.0.5, mime-types@2.1.10, form-data@1.0.0-rc4, bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── moment@2.11.2
├── pretty-error@2.0.0 (utila@0.4.0, renderkid@2.0.0)
├── inquirer@0.11.4 (ansi-regex@2.0.0, strip-ansi@3.0.1, ansi-escapes@1.4.0, figures@1.5.0, rx-lite@3.1.2, through@2.3.8, cli-width@1.1.1, chalk@1.1.3, run-async@0.1.0, readline2@1.0.1, string-width@1.0.1, cli-cursor@1.0.2, lodash@3.10.1)
├── cheerio@0.19.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.0.0, htmlparser2@3.8.3, lodash@3.10.1)
└── lodash@4.0.1
root@node-2gb-nyc2-01:~# mongo-edu -d ~/videos


 [ MONGO-EDU 0.2.53 ]


? MongoDB Uni User Name lorem@lipsum.com
? MongoDB Uni Password ********
> Searching [====================] 100%
? Select Courses: Current
? Hi Lorem 😄  Found 2 Courses. Select: M101JS: MongoDB for Node.js Developers
i Unable to locate any videos lists in the wiki. Are videos list present?
? Default wiki search returned no resuts. Perform courseware search with --cw ? Yes
i Unable to locate any videos lists in the wiki. Are videos list present?
root@node-2gb-nyc2-01:~# 
```

**Comment by przemyslawpluta** [comment]
@tropicloud this looks like your account issue as per https://github.com/przemyslawpluta/mongo-edu/issues/72 ... tested again against `node v4.4.3` and `Ubuntu 14.04.4 LTS` can't see any issues here:

``` bash
? MongoDB Uni User Name me@you.com
? MongoDB Uni Password ***
> Searching [====================] 100%
? Select Courses: Current
? Hi Chris 😄  Found 7 Courses. Select: M101JS: MongoDB for Node.js Developers
i Unable to locate any videos lists in the wiki. Are videos list present?
? Default wiki search returned no resuts. Perform courseware search with --cw ? Yes
? Found 8 Lists. Select: Week 6: The Aggregation Framework
> Searching Courseware [====================] 100%
> Collecting [====================] 100%
? Select From 5 Videos. Download: (Press <space> to select)
❯◉ All
 ◯ Cancel
 ◯ Introduction to the Aggregation Framework - 1280x720
 ◯ using accumulators in project - 1280x720
 ◯ intro to $group - 1280x720
 ◯ id in group stages - 1280x720
 ◯ group vs project - 1280x720
```

**Comment by tropicloud-2k** [comment]
@przemyslawpluta thanks for your quick reply and sorry about disturbing you with this.
I'll contact MongoDB University and will let you know about any updates.

Cheers!

**Comment by tropicloud-2k** [comment]
Well...

> It does not look like there is any problem with your account. Perhaps you could post your question in the course discussion forum, there may be others using the tool there.
> 
> Sincerely,
> MongoDB University Support

It sems we are alone in the dark.
Thanks anyway @przemyslawpluta

**Comment by przemyslawpluta** [comment]
@tropicloud for a test can you create a new account, subscribe to the lesson and try to download using this one. Let's see if you'll get the same issue ... Let me know.

**Comment by przemyslawpluta** [comment]
@tropicloud let me know if new account produced different results.

**Comment by tgkprog** [comment]
I have an account that I made in Feb 2016. Signed up for one course - for Java developers.

Similar error on windows 8:

<p>On windows. Installed node &amp; npm via msi. </p>

<blockquote>
  <p>node -v
<br>
  v4.4.3</p>
  <p>python -V
<br>
  Python 3.4.3</p>
</blockquote>

<pre><code>D:\learn\mongo\downloadCourse&gt;mongo-edu -d D:\learn\mongo\downloadCourse  --cw --hq --cc --ncc
[ MONGO-EDU 0.2.53 ]   
 (User and  Password)
&gt; Searching [====================] 100%
? Select Courses: Current
? Hi Tushar. Found 1 Course. Select: M101J: MongoDB for Java Developers
i Unable to locate any videos lists in the wiki. Are videos list present?
</code></pre>

<p>Any more flags to pass for windows? Does it work on Ubuntu? </p>

<p>For -h it worked - downloaded handouts. Refered <a href="https://github.com/przemyslawpluta/mongo-edu">https://github.com/przemyslawpluta/mongo-edu</a></p>

**Comment by yahyaKacem** [comment]
Still having this problem like @tgkprog said handouts works, but videos I get the same error:
>i Unable to locate any videos lists in the wiki. Are videos list present?

For both completed and current courses.
Is this fixed yet?
Or am I doing something wrong?
