### ISSUE TITLE
previous installed youtube-dl

### ISSUE THREAD

**Issue by zanemarkson** [przemyslawpluta/mongo-edu#75]
##### I am using Mac OS 10.10.5. I previously installed youtube-dl via homebrew and now it seems that npm cannot use the existing copy of youtube-dl:

> verbose stack Error: ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl'

**Comment by przemyslawpluta** [comment]
@zanemarkson please post entire console log you see during the installation process.

**Comment by rajivvishwa** [comment]
I have the exact same issue. Adding my console output since @zanemarkson has not replied yet.
I tried installing youtube-dl via npm and I can see it in `/usr/local/lib/node_modules/youtube-dl`

```
mac:Node rajivvishwa$ sudo npm install mongo-edu -g
npm WARN lifecycle youtube-dl@1.10.5~preinstall: cannot run in wd %s %s (wd=%s) youtube-dl@1.10.5 node ./scripts/download.js /usr/local/lib/node_modules/.staging/youtube-dl-146f77c2
/usr/local/lib
└── (empty)

npm ERR! Darwin 13.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mongo-edu" "-g"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! path /usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rajivvishwa/Projects/Node/npm-debug.log
npm ERR! code 1
```

Let me know if you need the debug log as well

**Comment by przemyslawpluta** [comment]
@rajivvishwa looks like your sudo user doesn't have write access to directory. Try to change the ownership of `/usr/local` have a look here [fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

**Comment by zanemarkson** [comment]
@przemyslawpluta Sorry for such a late response. I just found out that I did not have permission to write my **_/usr/local/lib/node_modules_** directory and now it is fixed and I have installed mongo-edu. **Thank you for your help!**
