### ISSUE TITLE
Problems in installing mongo-edu on a Windows 7 machine

### ISSUE THREAD

**Issue by drjf** [przemyslawpluta/mongo-edu#76]
Hi,
I have got node v4.4.3, npm 2.15.1, phthon 2.7.9 installed, and then I ran 
C:>npm install mongo-edu -g

> youtube-dl@1.10.5 preinstall C:\Users\junkang\AppData\Roaming\npm;npm\npm\node
> _modules\mongo-edu\node_modules\youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
Downloaded youtube-dl 2016.05.01
C:\Users\junkang\AppData\Roaming\npm;npm\npm\mongo-edu -> C:\Users\junkang\AppDa
ta\Roaming\npm;npm\npm\node_modules\mongo-edu\bin\mongo-edu

> mongo-edu@0.2.53 postinstall C:\Users\junkang\AppData\Roaming\npm;npm\npm\node
> _modules\mongo-edu
> node ./.resume/deploy

Resume option for youtube-dl deployed

mongo-edu@0.2.53 C:\Users\junkang\AppData\Roaming\npm;npm\npm\node_modules\mongo
-edu
├── easy-table@1.0.0
├── get-youtube-id@1.0.0
├── progress@1.1.8
├── path-extra@3.0.0
├── filesize@3.1.6
├── colors@1.1.2
├── request-progress@1.0.2 (throttleit@1.0.0)
├── which@1.2.4 (isexe@1.1.2, is-absolute@0.1.7)
├── mv@2.1.1 (rimraf@2.4.5, ncp@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@6.0.4 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3
.3, minimatch@3.0.0)
├── yargs@3.31.0 (decamelize@1.2.0, camelcase@2.1.1, y18n@3.2.1, window-size@0.1
.4, string-width@1.0.1, os-locale@1.4.0, cliui@3.2.0)
├── rimraf@2.5.2 (glob@7.0.3)
├── extract-zip@1.4.1 (debug@0.7.4, yauzl@2.4.1, mkdirp@0.5.0, concat-stream@1.5
.0)
├── youtube-dl@1.10.5 (streamify@0.2.5)
├── request@2.67.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oa
uth-sign@0.8.1, caseless@0.11.0, is-typedarray@1.0.0, stringstream@0.0.5, isstre
am@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, qs@5.2.0,
 node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4,
 bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── moment@2.11.2
├── pretty-error@2.0.0 (utila@0.4.0, renderkid@2.0.0)
├── cheerio@0.19.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.0.0, html
parser2@3.8.3, lodash@3.10.1)
├── inquirer@0.11.4 (strip-ansi@3.0.1, ansi-regex@2.0.0, ansi-escapes@1.4.0, fig
ures@1.5.0, rx-lite@3.1.2, through@2.3.8, cli-width@1.1.1, chalk@1.1.3, string-w
idth@1.0.1, readline2@1.0.1, cli-cursor@1.0.2, run-async@0.1.0, lodash@3.10.1)
└── lodash@4.0.1

then I ran
C:>mongo-edu --help
'mongo-edu' is not recognized as an internal or external command,
operable program or batch file.

Will you please help, which would be much appreciated.
Many thanks in anticipation
drjf

**Comment by przemyslawpluta** [comment]
Do you still get this after you've reopened the console?

**Comment by drjf** [comment]
Hi,
Thank you for your prompt response. I re-started my laptop and it is still the same:
C:\Users\junkang>mongo-edu --help
'mongo-edu' is not recognized as an internal or external command,
operable program or batch file.

I can see mongo-edu directory. But how can we tell whether mongo-edu has been installed or not please?
Many thanks in advance,
drjf

**Comment by drjf** [comment]
Hi
Sorry but I closed the question by mistake yesterday. Will you please take a look at my question above?
Many thanks
drjf

**Comment by przemyslawpluta** [comment]
@drjf please post entire output during installation

**Comment by drjf** [comment]
Hi, 
Thanks for your reply. The entire output during installation is as follows:

C:\Users\junkang>npm install mongo-edu -g

> youtube-dl@1.10.5 preinstall C:\Users\junkang\AppData\Roaming\npm;npm\npm\node
> _modules\mongo-edu\node_modules\youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
Downloaded youtube-dl 2016.05.01
C:\Users\junkang\AppData\Roaming\npm;npm\npm\mongo-edu -> C:\Users\junkang\AppDa
ta\Roaming\npm;npm\npm\node_modules\mongo-edu\bin\mongo-edu

> mongo-edu@0.2.53 postinstall C:\Users\junkang\AppData\Roaming\npm;npm\npm\node
> _modules\mongo-edu
> node ./.resume/deploy

Resume option for youtube-dl deployed

mongo-edu@0.2.53 C:\Users\junkang\AppData\Roaming\npm;npm\npm\node_modules\mongo
-edu
├── easy-table@1.0.0
├── get-youtube-id@1.0.0
├── path-extra@3.0.0
├── progress@1.1.8
├── filesize@3.1.6
├── colors@1.1.2
├── request-progress@1.0.2 (throttleit@1.0.0)
├── which@1.2.8 (isexe@1.1.2, is-absolute@0.1.7)
├── mv@2.1.1 (rimraf@2.4.5, ncp@2.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@6.0.4 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3
.3, minimatch@3.0.0)
├── rimraf@2.5.2 (glob@7.0.3)
├── yargs@3.31.0 (decamelize@1.2.0, camelcase@2.1.1, y18n@3.2.1, window-size@0.1
.4, string-width@1.0.1, cliui@3.2.0, os-locale@1.4.0)
├── extract-zip@1.4.1 (debug@0.7.4, mkdirp@0.5.0, yauzl@2.4.1, concat-stream@1.5
.0)
├── youtube-dl@1.10.5 (streamify@0.2.5)
├── moment@2.11.2
├── request@2.67.0 (aws-sign2@0.6.0, forever-agent@0.6.1, is-typedarray@1.0.0, c
aseless@0.11.0, tunnel-agent@0.4.3, oauth-sign@0.8.2, stringstream@0.0.5, isstre
am@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, tough-cookie@2.2.2, qs@5.2.0,
 node-uuid@1.4.7, combined-stream@1.0.5, mime-types@2.1.11, form-data@1.0.0-rc4,
 bl@1.0.3, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
├── pretty-error@2.0.0 (utila@0.4.0, renderkid@2.0.0)
├── inquirer@0.11.4 (strip-ansi@3.0.1, figures@1.5.0, ansi-escapes@1.4.0, ansi-r
egex@2.0.0, rx-lite@3.1.2, through@2.3.8, cli-width@1.1.1, chalk@1.1.3, string-w
idth@1.0.1, readline2@1.0.1, cli-cursor@1.0.2, run-async@0.1.0, lodash@3.10.1)
├── lodash@4.0.1
└── cheerio@0.19.0 (entities@1.1.1, dom-serializer@0.1.0, css-select@1.0.0, html
parser2@3.8.3, lodash@3.10.1)

Many thanks
drjf

**Comment by przemyslawpluta** [comment]
@drjf what do you get when you run `npm ls -g`

**Comment by drjf** [comment]
Hi,
This is all I get: 
C:\Users\junkang>npm ls -g
C:\Users\junkang\AppData\Roaming\npm;npm\npm
└─┬ mongo-edu@0.2.53
  ├─┬ cheerio@0.19.0
  │ ├─┬ css-select@1.0.0
  │ │ ├── boolbase@1.0.0
  │ │ ├── css-what@1.0.0
  │ │ ├─┬ domutils@1.4.3
  │ │ │ └── domelementtype@1.3.0
  │ │ └── nth-check@1.0.1
  │ ├─┬ dom-serializer@0.1.0
  │ │ └── domelementtype@1.1.3
  │ ├── entities@1.1.1
  │ ├─┬ htmlparser2@3.8.3
  │ │ ├── domelementtype@1.3.0
  │ │ ├── domhandler@2.3.0
  │ │ ├── domutils@1.5.1
  │ │ ├── entities@1.0.0
  │ │ └─┬ readable-stream@1.1.14
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ └── lodash@3.10.1
  ├── colors@1.1.2
  ├── easy-table@1.0.0
  ├─┬ extract-zip@1.4.1
  │ ├─┬ concat-stream@1.5.0
  │ │ ├── inherits@2.0.1
  │ │ ├─┬ readable-stream@2.0.6
  │ │ │ ├── core-util-is@1.0.2
  │ │ │ ├── isarray@1.0.0
  │ │ │ ├── process-nextick-args@1.0.7
  │ │ │ ├── string_decoder@0.10.31
  │ │ │ └── util-deprecate@1.0.2
  │ │ └── typedarray@0.0.6
  │ ├── debug@0.7.4
  │ ├─┬ mkdirp@0.5.0
  │ │ └── minimist@0.0.8
  │ └─┬ yauzl@2.4.1
  │   └─┬ fd-slicer@1.0.1
  │     └── pend@1.2.0
  ├── filesize@3.1.6
  ├── get-youtube-id@1.0.0
  ├─┬ glob@6.0.4
  │ ├─┬ inflight@1.0.4
  │ │ └── wrappy@1.0.1
  │ ├── inherits@2.0.1
  │ ├─┬ minimatch@3.0.0
  │ │ └─┬ brace-expansion@1.1.4
  │ │   ├── balanced-match@0.4.1
  │ │   └── concat-map@0.0.1
  │ ├─┬ once@1.3.3
  │ │ └── wrappy@1.0.1
  │ └── path-is-absolute@1.0.0
  ├─┬ inquirer@0.11.4
  │ ├── ansi-escapes@1.4.0
  │ ├── ansi-regex@2.0.0
  │ ├─┬ chalk@1.1.3
  │ │ ├── ansi-styles@2.2.1
  │ │ ├── escape-string-regexp@1.0.5
  │ │ ├── has-ansi@2.0.0
  │ │ └── supports-color@2.0.0
  │ ├─┬ cli-cursor@1.0.2
  │ │ └─┬ restore-cursor@1.0.1
  │ │   ├── exit-hook@1.1.1
  │ │   └── onetime@1.1.0
  │ ├── cli-width@1.1.1
  │ ├── figures@1.5.0
  │ ├── lodash@3.10.1
  │ ├─┬ readline2@1.0.1
  │ │ ├─┬ code-point-at@1.0.0
  │ │ │ └── number-is-nan@1.0.0
  │ │ ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │ └── number-is-nan@1.0.0
  │ │ └── mute-stream@0.0.5
  │ ├─┬ run-async@0.1.0
  │ │ └─┬ once@1.3.3
  │ │   └── wrappy@1.0.1
  │ ├── rx-lite@3.1.2
  │ ├─┬ string-width@1.0.1
  │ │ ├─┬ code-point-at@1.0.0
  │ │ │ └── number-is-nan@1.0.0
  │ │ └─┬ is-fullwidth-code-point@1.0.0
  │ │   └── number-is-nan@1.0.0
  │ ├── strip-ansi@3.0.1
  │ └── through@2.3.8
  ├── lodash@4.0.1
  ├─┬ mkdirp@0.5.1
  │ └── minimist@0.0.8
  ├── moment@2.11.2
  ├─┬ mv@2.1.1
  │ ├── ncp@2.0.0
  │ └── rimraf@2.4.5
  ├── path-extra@3.0.0
  ├─┬ pretty-error@2.0.0
  │ ├─┬ renderkid@2.0.0
  │ │ ├─┬ css-select@1.2.0
  │ │ │ ├── boolbase@1.0.0
  │ │ │ ├── css-what@2.1.0
  │ │ │ ├─┬ domutils@1.5.1
  │ │ │ │ ├─┬ dom-serializer@0.1.0
  │ │ │ │ │ ├── domelementtype@1.1.3
  │ │ │ │ │ └── entities@1.1.1
  │ │ │ │ └── domelementtype@1.3.0
  │ │ │ └── nth-check@1.0.1
  │ │ ├── dom-converter@0.1.4
  │ │ ├─┬ htmlparser2@3.3.0
  │ │ │ ├── domelementtype@1.3.0
  │ │ │ ├── domhandler@2.1.0
  │ │ │ ├── domutils@1.1.6
  │ │ │ └─┬ readable-stream@1.0.34
  │ │ │   ├── core-util-is@1.0.2
  │ │ │   ├── inherits@2.0.1
  │ │ │   ├── isarray@0.0.1
  │ │ │   └── string_decoder@0.10.31
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.0.0
  │ │ └── utila@0.3.3
  │ └── utila@0.4.0
  ├── progress@1.1.8
  ├─┬ request@2.67.0
  │ ├── aws-sign2@0.6.0
  │ ├─┬ bl@1.0.3
  │ │ └─┬ readable-stream@2.0.6
  │ │   ├── core-util-is@1.0.2
  │ │   ├── inherits@2.0.1
  │ │   ├── isarray@1.0.0
  │ │   ├── process-nextick-args@1.0.7
  │ │   ├── string_decoder@0.10.31
  │ │   └── util-deprecate@1.0.2
  │ ├── caseless@0.11.0
  │ ├─┬ combined-stream@1.0.5
  │ │ └── delayed-stream@1.0.0
  │ ├── extend@3.0.0
  │ ├── forever-agent@0.6.1
  │ ├─┬ form-data@1.0.0-rc4
  │ │ └── async@1.5.2
  │ ├─┬ har-validator@2.0.6
  │ │ ├─┬ chalk@1.1.3
  │ │ │ ├── ansi-styles@2.2.1
  │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ └── supports-color@2.0.0
  │ │ ├─┬ commander@2.9.0
  │ │ │ └── graceful-readlink@1.0.1
  │ │ ├─┬ is-my-json-valid@2.13.1
  │ │ │ ├── generate-function@2.0.0
  │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ └── is-property@1.0.2
  │ │ │ ├── jsonpointer@2.0.0
  │ │ │ └── xtend@4.0.1
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ ├─┬ hawk@3.1.3
  │ │ ├── boom@2.10.1
  │ │ ├── cryptiles@2.0.5
  │ │ ├── hoek@2.16.3
  │ │ └── sntp@1.0.9
  │ ├─┬ http-signature@1.1.1
  │ │ ├── assert-plus@0.2.0
  │ │ ├─┬ jsprim@1.2.2
  │ │ │ ├── extsprintf@1.0.2
  │ │ │ ├── json-schema@0.2.2
  │ │ │ └── verror@1.3.6
  │ │ └─┬ sshpk@1.8.3
  │ │   ├── asn1@0.2.3
  │ │   ├── assert-plus@1.0.0
  │ │   ├── dashdash@1.13.1
  │ │   ├── ecc-jsbn@0.1.1
  │ │   ├── getpass@0.1.6
  │ │   ├── jodid25519@1.0.2
  │ │   ├── jsbn@0.1.0
  │ │   └── tweetnacl@0.13.3
  │ ├── is-typedarray@1.0.0
  │ ├── isstream@0.1.2
  │ ├── json-stringify-safe@5.0.1
  │ ├─┬ mime-types@2.1.11
  │ │ └── mime-db@1.23.0
  │ ├── node-uuid@1.4.7
  │ ├── oauth-sign@0.8.2
  │ ├── qs@5.2.0
  │ ├── stringstream@0.0.5
  │ ├── tough-cookie@2.2.2
  │ └── tunnel-agent@0.4.3
  ├─┬ request-progress@1.0.2
  │ └── throttleit@1.0.0
  ├─┬ rimraf@2.5.2
  │ └─┬ glob@7.0.3
  │   ├─┬ inflight@1.0.4
  │   │ └── wrappy@1.0.1
  │   ├── inherits@2.0.1
  │   ├─┬ minimatch@3.0.0
  │   │ └─┬ brace-expansion@1.1.4
  │   │   ├── balanced-match@0.4.1
  │   │   └── concat-map@0.0.1
  │   ├─┬ once@1.3.3
  │   │ └── wrappy@1.0.1
  │   └── path-is-absolute@1.0.0
  ├─┬ which@1.2.8
  │ ├─┬ is-absolute@0.1.7
  │ │ └── is-relative@0.1.3
  │ └── isexe@1.1.2
  ├─┬ yargs@3.31.0
  │ ├── camelcase@2.1.1
  │ ├─┬ cliui@3.2.0
  │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ └── ansi-regex@2.0.0
  │ │ └── wrap-ansi@2.0.0
  │ ├── decamelize@1.2.0
  │ ├─┬ os-locale@1.4.0
  │ │ └─┬ lcid@1.0.0
  │ │   └── invert-kv@1.0.0
  │ ├─┬ string-width@1.0.1
  │ │ ├─┬ code-point-at@1.0.0
  │ │ │ └── number-is-nan@1.0.0
  │ │ ├─┬ is-fullwidth-code-point@1.0.0
  │ │ │ └── number-is-nan@1.0.0
  │ │ └─┬ strip-ansi@3.0.1
  │ │   └── ansi-regex@2.0.0
  │ ├── window-size@0.1.4
  │ └── y18n@3.2.1
  └─┬ youtube-dl@1.10.5
    └─┬ streamify@0.2.5
      └─┬ hashish@0.0.4
        └── traverse@0.6.6

Thank you!
drjf

**Comment by przemyslawpluta** [comment]
Seem to be installed ... can you uninstall first then do `npm cache clean` and reinstall mongo-edu.

**Comment by drjf** [comment]
I am really sorry to bother you but I seem to have had mongo-edu uninstalled, but  'npm cache clean' gave me lots of npm errors, and again lots of errors when I tried to install mongo-edu again:

C:\Users\junkang>npm uninstall mongo-edu
unbuild mongo-edu@0.1.3

C:\Users\junkang>npm cache clean
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "cache" "clean"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path C:\Users\junkang\AppData\Roaming\npm;npm\npm-cache
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rmdir

npm ERR! Error: EPERM: operation not permitted, rmdir 'C:\Users\junkang\AppData\
Roaming\npm;npm\npm-cache'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rmdir 'C:\Users\junkang\AppD
ata\Roaming\npm;npm\npm-cache']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rmdir',
npm ERR!   path: 'C:\Users\junkang\AppData\Roaming\npm;npm\npm-cache' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\junkang\npm-debug.log

C:\Users\junkang>npm install mongo-edu -g

> youtube-dl@1.10.5 preinstall C:\Users\junkang\AppData\Roaming\npm;npm\npm\node
> _modules\mongo-edu\node_modules\youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
Downloaded youtube-dl 2016.05.01
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install" "mongo-edu" "-g"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! path C:\Users\junkang\AppData\Roaming\npm;npm\npm-cache\lodash\3.10.1\p
ackage.tgz.2479773732
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\junkang\AppData
\Roaming\npm;npm\npm-cache\lodash\3.10.1\package.tgz.2479773732' -> 'C:\Users\ju
nkang\AppData\Roaming\npm;npm\npm-cache\lodash\3.10.1\package.tgz'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\junkang\App
Data\Roaming\npm;npm\npm-cache\lodash\3.10.1\package.tgz.2479773732' -> 'C:\User
s\junkang\AppData\Roaming\npm;npm\npm-cache\lodash\3.10.1\package.tgz']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\Users\junkang\AppData\Roaming\npm;npm\npm-cache\loda
sh\3.10.1\package.tgz.2479773732',
npm ERR!   dest: 'C:\Users\junkang\AppData\Roaming\npm;npm\npm-cache\loda
sh\3.10.1\package.tgz',
npm ERR!   parent: 'cheerio' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\junkang\npm-debug.log

Will you please advise me further?
Many thanks
drjf

**Comment by drjf** [comment]
Hi, 
While I am waiting for your further advice, I am wondering if I have done the right thing in using npm, see below, to uninstall mongo-edu please:

C:\Users\junkang>npm uninstall mongo-edu
unbuild mongo-edu@0.1.3

Your help would be much appreciated.
drjf

**Comment by drjf** [comment]
Hi,
Just to let you know that I have finally got mongo-edu working by following your advice to have done the following:

> npm uninstall mongo-edu -g
> npm cache clean
> npm install mong-edu -g

Many thanks again!
dr jf
