### ISSUE TITLE
mongo-edu installing issue .

### ISSUE THREAD

**Issue by medaamarnadh** [przemyslawpluta/mongo-edu#77]
Hi I am using node 5.6.0 on mac . 
I am getting following error when i give npm install -g mongo-edu

> youtube-dl@1.10.5 preinstall /Users/scriptbees/.nvm/versions/node/v5.6.0/lib/node_modules/.staging/youtube-dl-f54519aa
> node ./scripts/download.js

Downloading latest youtube-dl
/Users/scriptbees/.nvm/versions/node/v5.6.0/lib/node_modules/.staging/youtube-dl-f54519aa/scripts/download.js:19
  throw err;
  ^

Error: Response Error: 302
    at ClientRequest.<anonymous> (/Users/scriptbees/.nvm/versions/node/v5.6.0/lib/node_modules/.staging/youtube-dl-f54519aa/scripts/download.js:65:16)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:425:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
    at TLSSocket.socketOnData (_http_client.js:315:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
/Users/scriptbees/.nvm/versions/node/v5.6.0/lib
└── (empty)

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/scriptbees/.nvm/versions/node/v5.6.0/bin/node" "/Users/scriptbees/.nvm/versions/node/v5.6.0/bin/npm" "install" "mongo-edu"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.10.5 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl@1.10.5 preinstall script 'node ./scripts/download.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/scriptbees/.nvm/versions/node/v5.6.0/lib/node_modules/npm-debug.log
npm ERR! code 1

**Comment by jaykodeveloper** [comment]
I have same issue. Did you figure out?

**Comment by tssr2001** [comment]
yes, me too... can you please help to resolve this issue?
Attached the npm-debug.log for your reference.

[npm-debug.zip](https://github.com/przemyslawpluta/mongo-edu/files/302713/npm-debug.zip)

**Comment by biruelrick** [comment]
Me too... the same problem!

**Comment by przemyslawpluta** [comment]
What OS and mongo-edu version are you running?

**Comment by beezischillin** [comment]
Having the same issue on all of my machines, latest NodeJS, OSX ElCap latest update on both of my Macs, Windows 10 on my PC, latest mongo-edu -- I guess?

**Comment by ipmas** [comment]
I've made a [pull request](https://github.com/przemyslawpluta/mongo-edu/pull/79) fixing the issue. Anyone should be able to get this downloader running by performing the same change to a locally cloned repository and installing it using the instructions at [this stackoverflow page](http://stackoverflow.com/questions/8088795/installing-a-local-module-using-npm)

**Comment by biruelrick** [comment]
I'm using mac, I did this [issue](http://stackoverflow.com/questions/37683519/error-installing-the-mongo-edu-on-mac) on stackover with details.

**Comment by learnudon** [comment]
OS - Ubuntu 16.04
node version - 4.4.7
npm version - 2.15.8
python version - 2.7.11

i am not sure whether i understand or follow the "stackoverlow" instruction correctly.
1. there are no youtube-dl modules in directory /usr/lib/node_modules/npm/node_modules/
2a. there is however another directoriy which seems to contain more node_modules in /home/"user"/.npm
2b. both youtube-dl 1.10.5 and 1.11.1 are present in directory /home/"user"/.npm/youtube-dl

so this is what i do
$ cd /home/"user"/.npm/youtube-dl/1.11.5/package
$ npm link

now i have download and extract mongo-edu onto this directory /home/"user"/mongo-edu-master
am i correct to assume this is the project directory?
i change line 54( "youtube-dl": "~1.10.5" to  "youtube-dl": "~1.11.1")
to the package.json in the mongo-edu-master directory before typing the following command:

$ cd /home/"user"/mongo-edu-master
$ npm link youtube-dl@1.11.1

assuming that all the steps are correct. how do i run mongo-edu, or what the next step is?

i really have no idea on what i  am suppose to do. 
Any help is really appreciated.
below is the error shown when i later try to install mongo-edu via this command:
$ sudo npm install /home/"user"/mongo-edu-master/ -g 

> youtube-dl@1.11.1 postinstall /usr/lib/node_modules/mongo-edu/node_modules/youtube-dl
> node ./scripts/download.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'generate-object-property'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/mongo-edu/node_modules/request/node_modules/har-validator/node_modules/is-my-json-valid/index.js:1:76)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mongo-edu-master/" "-g"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE

the rest are the same as the previous post
