### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by girishgupta211-zz** [przemyslawpluta/mongo-edu#81]
[~girish] > sudo npm install mongo-edu -g 

> youtube-dl@1.10.5 preinstall /usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js:19
  throw err;
  ^

Error: Response Error: 302
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js:65:16)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:415:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at TLSSocket.socketOnData (_http_client.js:305:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "install" "mongo-edu" "-g"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.10.5 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.10.5 preinstall script 'node ./scripts/download.js'.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ggirgup/npm-debug.log

**Comment by harryzhux** [comment]
Got the same problem when run without sudo:
% npm install mongo-edu -g

> youtube-dl@1.10.5 preinstall /home/zhu/.nvm/versions/node/v4.4.5/lib/node_modules/mongo-edu/node_modules/youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
/home/zhu/.nvm/versions/node/v4.4.5/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js:19
  throw err;
  ^

Error: Response Error: 302
    at ClientRequest.<anonymous> (/home/zhu/.nvm/versions/node/v4.4.5/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js:65:16)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/home/zhu/.nvm/versions/node/v4.4.5/bin/node" "/home/zhu/.nvm/versions/node/v4.4.5/bin/npm" "install" "mongo-edu" "-g"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.10.5 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.10.5 preinstall script 'node ./scripts/download.js'.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zhu/npm-debug.log

With sudo, a different error:
% sudo npm install mongo-edu -g
npm WARN lifecycle youtube-dl@1.10.5~preinstall: cannot run in wd %s %s (wd=%s) youtube-dl@1.10.5 node ./scripts/download.js /usr/lib/node_modules/.staging/youtube-dl-8a05e31e
/usr/lib
└── (empty)

npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "mongo-edu" "-g"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! path /usr/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl'
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/lib/node_modules/mongo-edu/node_modules/youtube-dl/bin/youtube-dl'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zhu/npm-debug.log
npm ERR! code 1

**Comment by andreasmacht** [comment]
I'm running on Ubuntu 14.04 LTS and have the same error with sudo command like a.m. 

`sudo npm install mongo-edu -g

> youtube-dl@1.10.5 preinstall /usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js:19
  throw err;
  ^

Error: Response Error: 302
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/mongo-edu/node_modules/youtube-dl/scripts/download.js:65:16)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
npm ERR! Linux 3.19.0-64-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mongo-edu" "-g"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.10.5 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the youtube-dl@1.10.5 preinstall script 'node ./scripts/download.js'.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/andreasmacht/Documents/MONGODB UNIVERSITY/mongo-edu-master/npm-debug.log
[npm-debug.log.zip](https://github.com/przemyslawpluta/mongo-edu/files/355870/npm-debug.log.zip)

`

**Comment by samplewm** [comment]
mongo-edu-master>npm install

> \mongo-edu-master\mongo-edu-master\node_modules\youtube-dl
> node ./scripts/download.js

Downloading latest youtube-dl
\node_modules\youtube-dl\scripts\download.js:19
  throw err;
  ^

Error: Response Error: 302
    at ClientRequest.<anonymous> (\mongo-edu-master\node_modules\youtube-dl\scripts\download.js:65:16)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:430:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:320:20)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! youtube-dl@1.10.5 preinstall: `node ./scripts/download.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the youtube-dl@1.10.5 preinstall script 'node ./scripts/downl
oad.js'.
npm ERR! This is most likely a problem with the youtube-dl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/download.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs youtube-dl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls youtube-dl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     \mongo-edu-master\npm-debug.log

**Comment by nsantiago2719** [comment]
Try to use for the mean time the forked repo of pitchdiesel it work for me. Clone his repo then install..

**Comment by seanmavley** [comment]
@nsantiago2719 And after cloning, how did you install? `npm install mongo-edu g` from the project directory?

**Comment by andreasmacht** [comment]
yes

2016-11-15 17:23 GMT+03:00 Nkansah Rexford notifications@github.com:
