### ISSUE TITLE
List of videos not found ?

### ISSUE THREAD

**Issue by AlirezaSadeghi** [przemyslawpluta/mongo-edu#85]
Hi,

There seem to be a problem with the script in which it can't find the list of videos in the course, is that expected ?

The selected course have not ended as evident from the website ( as of now, 22Nov, 2016), but it can't find them.

""""""""" LOG """""""""
> Searching [====================] 100%
? Select Courses: Current
? Hi Alireza 😄  Found 3 Courses. Select: M102: MongoDB for DBAs
i Unable to locate any videos lists in the wiki. Are videos list present?
? Default wiki search returned no resuts. Perform courseware search with --cw ? Yes
i Looks like the course is not yet available or has already ended. Videos list is not available.

Check the start/end date for selected course.
""""" END LOG """""

Any ideas ?

![image](https://cloud.githubusercontent.com/assets/2128505/20534767/acb8e970-b0f7-11e6-898c-f01d8b201cc8.png)

**Comment by alegar44** [comment]
I have the same issue. I cannot download any videos from my past or current courses. Does anyone has found a workaround?
