### ISSUE TITLE
mongo-edu installation issue. Giving error related to youtube-dl

### ISSUE THREAD

**Issue by ashmeetchhabra** [przemyslawpluta/mongo-edu#86]
mongo-edu installation issue. Giving error related to youtube-dl
![screenshot from 2017-09-03 02-08-15](https://user-images.githubusercontent.com/13083177/29998608-117f703e-901f-11e7-850f-71313f54cbb2.png)

**Comment by przemyslawpluta** [comment]
Please read https://github.com/przemyslawpluta/mongo-edu/issues/87
