### ISSUE TITLE
download videos using the mongo-edu failed with exception

### ISSUE THREAD

**Issue by rajsreenath** [przemyslawpluta/mongo-edu#9]
I get the following error when I try to download videos using the mongo-edu utility. Please advise.

C:\Program Files\nodejs>mongo-edu -d C:\Program Files\nodejs\videos
[?] MongoDB Uni User Name: abcd@mongodb.com
[?] MongoDB Uni Password: **********
[>] Searching [===================] 100%
[?] Found 3 Courses. Select: M102: MongoDB for DBAs
[?] Found 7 Lists. Select: Week 1 Video Links
[?] Select From 22 Videos. Download:  https://www.youtube.com/watch?v=0euni8AdT1
c

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)

**Comment by pridemusvaire** [comment]
mine fails after downloading a couple of videos, is there a way to skip already downloaded videos like in youtube-dl

**Comment by przemyslawpluta** [comment]
@pridemusvaire screen grab would be helpful.

**Comment by pridemusvaire** [comment]
let me send it


On Fri, Aug 28, 2015 at 3:59 PM, Przemyslaw Pluta <notifications@github.com>
wrote:

> @pridemusvaire <https://github.com/pridemusvaire> screen grab would be
> helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/przemyslawpluta/mongo-edu/issues/9#issuecomment-135781539>
> .
>



-- 
pmuvaire

**Comment by pridemusvaire** [comment]
[image: Inline image 1]

On Fri, Aug 28, 2015 at 4:00 PM, Pride Tafadzwa Musvaire <
musvairepridetafadzwa@gmail.com> wrote:

> let me send it
>
>
> On Fri, Aug 28, 2015 at 3:59 PM, Przemyslaw Pluta <
> notifications@github.com> wrote:
>
>> @pridemusvaire <https://github.com/pridemusvaire> screen grab would be
>> helpful.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/przemyslawpluta/mongo-edu/issues/9#issuecomment-135781539>
>> .
>>
>
>
>
> --
> pmuvaire
>



-- 
pmuvaire

**Comment by pridemusvaire** [comment]
![mongo](https://cloud.githubusercontent.com/assets/8037540/9637926/e26b2a60-51a3-11e5-9c25-9a6db12ad3e9.PNG)

**Comment by pridemusvaire** [comment]
isn't there a way to make mongo-edu to skip already downloaded content, like youtube-dl

**Comment by przemyslawpluta** [comment]
Looks like an issue with python or your network. Try to reinstall python.

**Comment by pridemusvaire** [comment]
thanks for the advice bro

On Wed, Sep 2, 2015 at 9:32 PM, Przemyslaw Pluta <notifications@github.com>
wrote:

> Looks like an issue with python or your network. Try to reinstall python.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/przemyslawpluta/mongo-edu/issues/9#issuecomment-137221671>
> .
>



-- 
pmuvaire

**Comment by pridemusvaire** [comment]
a,
    a:visited {
        color: #D26000;
        text-decoration: none;
    }


    
        
            
            
                
                    
                        
                            
                                
                                    
                                        
                                    
                                
                            
                        
                    
                
            
            
            
            
                
                    
                        


    
        
             
        
    




    
        
            
                
                    
                
            
            
                
                    Join me on PeoplePerHour
                
            
        
        
            
                
                    
                
                
                    I have been using PeoplePerHour.com a marketplace connecting curated freelance talent with remote work, anything from 1 hour upwards.
                
            
        
    






    
    	
    		
    			
                	ACCEPT INVITATION
            	
        	
        
    



                    
                
            
            
            
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                    
                                                    
                                                        
                                                    
                                                
                                            
                                        
                                        
                                            
                                                
                                                    
                                                        © 2007 - 2015 PeoplePerHour All rights reserved                                                    
                                                    
                                                        This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here

**Comment by pridemusvaire** [comment]
```
a,
a:visited {
    color: #D26000;
    text-decoration: none;
}































      News about Pride and other latest on PeoplePerHour
```

Hello,
Pride has been active on PeoplePerHour for 5 days now and they've invited you to join!
Accept the invitation today and get 10% off your first purchase on PeoplePerHour... it's great to have friends with benefits, right?

```
                Join now
```

Here's some of the latest activity on PeoplePerHour that you'll find interesting

```
                Add subtitles to video












                        Khaireddine L.





                                    $10























                Design 3 creative logo in 18 hours












                        Uroosa Ali M.





                                    $12


























                Design Business card+Flyer+Letter head+Envelope with unlimit...












                        Daniyal K.





                                    $10























                Send you 49 infographic templates in Powerpoint format and 1...












                        Rob W.





                                    $14


























                Illustrate anything you need












                        Selcuk A.





                                    $10























                Offer 1200 facebook likes or 3kTwitter or Instagram follower...












                        Web S.





                                    $10

















            Kind Regards,
            The PPH Team














































                                                    © 2007 - 2015 PeoplePerHour All rights reserved                                                    

                                                    This is an important notification helping you quickly get the most out of PeoplePerHour.  You can change your notification settings here
```
